use Uganda;
go

drop table if exists NDP3.Interventions;
go

create table NDP3.Interventions
(
	InterventionID int identity,
	ProgrammeNumber int,
	ObjectiveNumber int,
	InterventionNumber int, 
	Actors nvarchar(1000),
	constraint PK_Interventions primary key (InterventionID),
	constraint UQ_Interventions_POI unique (ProgrammeNumber,ObjectiveNumber,InterventionNumber)
);

insert NDP3.Interventions (ProgrammeNumber, ObjectiveNumber, InterventionNumber, Actors) values
(1  ,1  ,1  ,'MAAIF, MOICT, NITAU,  NARO, Universities,  Academic and vocational  institutions, Professional  bodies, International  research organizations,  CSOs, Public Research  organizations'),
(1  ,1  ,2  ,'MAAIF, NARO,  MoICT&NG, MoLG,  UCDA, DDA,  NAGRC&DB, CDO, LGs,  Extension service  providers, Private sector  companies, MDAs, NGOs'),
(1  ,1  ,3  ,'MAAIF, OWC, NAADS,  UNBS, LGs, UCDA,  DDA, NAGRC&DB,  CDO'),
(1  ,1  ,4  ,'MAAIF & MWE, MEMD,  Farmers, Cooperatives and  associations, UIA, Private  Sector, MTIC, MoFPED,  UMFSC, BOU'),
(1  ,1  ,5  ,'MAAIF, MTIC,  Universities, private  sector, vocational  institutions'),
(1  ,1  ,6  ,'MAAIF, MoICT, NITA-U,  UCC, UCDA, DDA,  NAGRC&DB, CDO,  NARO, NAADS'),
(1  ,1  ,7  ,'MAAIF, MLHUD, ULC,  NARO, NAGRC, UCDA,  CDO, DDA, NAADS'),
(1  ,1  ,8  ,'MAAIF, MTIC, UCDA,  DDA, NAGRC&DB,  CDO, NAADS, OWC,  LGs, Farmers,  Cooperatives and  associations'),
(1  ,1  ,9  ,'MAAIF, MOH, NARO,  Private Sector e.g Maama  Care'),
(1  ,1  ,10 ,'MAAIF, NFA, MLHUD,  UCDA, CDO, NAADS,  NARO, NAGRC&DB,  OWC, LGs'),
(1  ,1  ,11 ,'MAAIF, MoES, MTIC,  UCDA, CDO, NAADS,  NARO, NAGRC&DB,  OWC, DDA, LGs'),
(1  ,1  ,12 ,'UNMA, MAAIF '),
(1  ,1  ,13 ,'MOGLSD, MAAIF, NAC,  LGs'),
(1  ,2  ,1  ,'MAAIF, MTIC, UWRSA,  NAADS, OWC, DDA,  UCDA, CDO,  NAGRC&DB, LGs,  Private sector '),
(1  ,2  ,2  ,'MAAIF, MTIC, UWRSA,  NAADS, OWC, DDA,  UCDA, CDO,  NAGRC&DB, TGCU,  LGs'),
(1  ,2  ,3  ,'MAAIF, MTIC, UWRSA,  NAADS, OWC, MWT,  Private Sector'),
(1  ,3  ,1  ,'UIA, FZA, MAAIF,  MTIC, Private Sector'),
(1  ,3  ,2  ,'MAAIF, MoES, MTIC,  MDAs,  MAAIF, MoES, MTIC  MAAIF, Parliament, LRC,  UIA, MOFPED '),
(1  ,3  ,3  ,'MAAIF, DDA, MTIC,  LGs, UDC, NAADS,  PSFU, OWC, UCDA,  CDO, MTIC, MOH, NDA,  NAGRC&DB, NARO,  Academia, MoFPED,  UDC, UDB, Private sector'),
(1  ,3  ,4  ,'UEDCL, ERA '),
(1  ,3  ,5  ,'MWT, MAAIF'),
(1  ,3  ,6  ,'MoES, MAAF,  MTICUCDA, CDO, DDA,  NAGRC&DB, NAADS,  OWC'),
(1  ,4  ,1  ,'UNBS, MAAIF, MTIC'),
(1  ,4  ,2  ,'MAAIF, MICT, MTIC,  MOGLSD, UEPB, NITAU'),
(1  ,4  ,3  ,'MAAIF, MoLG, MTIC,  UWRSA, UCE '),
(1  ,4  ,4  ,'MAAIF, MTIC, MoWT,  URC, Private Sector, LGs'),
(1  ,4  ,5  ,'UEPB, MAAIF, MoFA,  UCDA, CDO, DDA'),
(1  ,5  ,1  ,'MAAIF, MOFPED, BOU,  UIRA, UDB, Financial  Institutions, MTIC, LGs'),
(1  ,5  ,2  ,'MOFPED, MAAIF UIRA'),
(1  ,5  ,3  ,'MAAIF, MTIC, UCA,  UNFFE '),
(1  ,5  ,4  ,'MOFPED, MAAIF,  MTIC, UWRSA, UCE,  MAAIF, USE, MTIC,  MOFPED, LGs, Private  Sector '),
(1  ,5  ,5  ,'UDB, MOFPED, UIA,  UDC, MAAIF, MTIC'),
(1  ,5  ,6  ,'MAAIF, MTIC'),
(1  ,6  ,1  ,'MAAIF, MOFPED,  MTIC, NAADS, PSFU,  CSOs, Private sector,  OWC'),
(1  ,6  ,2  ,'MAAIF, OPM, NPA,  Private Sector'),
(2  ,1  ,1  ,'MEMD, MFPED, MoPS,  DPs'),
(2  ,1  ,2  ,'MEMD, MFPED, Private  Sector, DPs'),
(2  ,1  ,3  ,'MEMD, DPs'),
(2  ,1  ,4  ,'MEMD, MTIC, MFPED,  NEMA, NPA, Academia,  DPs'),
(2  ,2  ,1  ,'MEMD, MTIC, LGs,  CSOs, DPs '),
(2  ,2  ,2  ,'MEMD, MFPED, UIA,  URA'),
(2  ,2  ,3  ,'MEMD, MSTI, UIRI,  MoES, UNCST, NCHE,  Academia, DPs'),
(2  ,2  ,4  ,'MEMD, MTIC, LGs,  BTVET, NCHE,  Academia, CSOs, DPs'),
(2  ,3  ,1  ,'MEMD, MTIC, MoJCA,  Parliament, Private  Sector, CSOs'),
(2  ,3  ,2  ,'MEMD, MoPS, LGs'),
(2  ,3  ,3  ,'MEMD, MTIC, MoES,  MGLSD, UMA, USSIA,  DIT, PSFU, CSOs, DPs,  Academic Institutions'),
(2  ,3  ,4  ,'MEMD, MFPED, UMA,  UCMP, Private Sector,  DPs'),
(2  ,3  ,5  ,'MEMD, MJCA,  Parliament, Cabinet  Secretariat  '),
(2  ,3  ,6  ,'MEMD, MTIC, MoWE,  NEMA, LGs, MoIA,  URA, UNBS, UPF,  UNCE'),
(2  ,3  ,7  ,'MEMD, MoPS, LGs'),
(2  ,3  ,8  ,'MEMD, LGs'),
(2  ,3  ,9  ,'MEMD, MoJCA,  MoGLSD, LGs,  Development Partners,  Parliament'),
(2  ,3  ,10 ,'MEMD'),
(2  ,3  ,11 ,'OPM, MEMD'),
(2  ,3  ,12 ,'MEMD'),
(2  ,4  ,1  ,'MEMD, MTIC, MFPED,  LGs, UIA'),
(2  ,4  ,2  ,'MEMD, MFPED, DPs'),
(2  ,4  ,3  ,'MEMD, MFPED, DPs'),
(2  ,4  ,4  ,'MEMD, MoSTI, MFPED,  MTIC, MoES, UNCST,  NCHE, Academia, UIRI,  DPs, Private Sector, UMA'),
(2  ,4  ,5  ,'MEMD, MFPED, MTIC,  UDC, UDB'),
(2  ,4  ,6  ,'MEMD, MFPED,  MoJCA, UDC, MTIC,  UIA, Private Sector,  Financial Institutions'),
(2  ,4  ,7  ,'MEMD'),
(2  ,4  ,8  ,'MEMD, UDC, MoFPED'),
(2  ,4  ,9  ,'MEMD, UNES'),
(2  ,5  ,1  ,'MEMD, MoFA, MTIC,  MFPED, MoJCAs,  UEPB, DPs'),
(2  ,5  ,2  ,'MEMD, MTIC, MFPED,  UIA, UDC, UDB,  Financial Institutions,  Private Sector'),
(2  ,5  ,3  ,'MEMD'),
(2  ,5  ,4  ,'URA, MoFPED, NPA'),
(2  ,5  ,5  ,'UNBS, MoFPED'),
(2  ,5  ,6  ,'MEMD, MoFA, MoFPED'),
(3  ,1  ,1  ,'MEMD, MoFPED, PAU,  UNOC, Joint Venture  Partners'),
(3  ,1  ,2  ,'MEMD, MoWT, UCAA,  UNRA, MoLHUD, PAU,  MWE, MoFPED, UNOC,  MoICT&NG, LGs'),
(3  ,1  ,3  ,'MEMD'),
(3  ,1  ,4  ,'MEMD, MOFPED, NEMA,  PAU, NPA, LGs'),
(3  ,1  ,5  ,'MEMD'),
(3  ,2  ,1  ,'MEMD, MoJCA, PAU,  UNOC, Parliament, Joint  Venture Partners'),
(3  ,2  ,2  ,'MEMD, MoJCA, PAU,  UNOC, Parliament, Joint  Venture Partners'),
(3  ,2  ,3  ,'MEMD'),
(3  ,2  ,4  ,'MEMD, MoJCA, MoES, PAU,  UNOC, Academia, Joint  Venture Partners, NCHE'),
(3  ,2  ,5  ,'MEMD, URA,  MoICT&NG'),
(3  ,2  ,6  ,'PAU, UNOC, BOU, MEMD,  MOFPED'),
(3  ,3  ,1  ,'MEMD, MoFPED, UDB'),
(3  ,3  ,2  ,'MEMD, MoFPED, UNOC,  PAU, Parliament'),
(3  ,3  ,3  ,'MEMD, MoJCA, MoES,  PAU, UNOC, Academia,  NCHE, Joint Venture  Partners'),
(3  ,3  ,4  ,'MEMD, PAU, other  MDAs'),
(3  ,3  ,5  ,'MEMD'),
(3  ,3  ,6  ,'MEMD, PAU, UNOC,  PSFU, Joint Venture  Partners'),
(3  ,3  ,7  ,'MEMD'),
(3  ,3  ,8  ,'MEMD, MAAIF'),
(3  ,4  ,1  ,'MOFPED, PSFU, UDB, UNOC'),
(3  ,4  ,2  ,'MEMD, UNOC, ICT, NITA_U,  PAU'),
(3  ,4  ,3  ,'MEMD, UNOC, ICT, NITA_U,  PAU'),
(3  ,5  ,1  ,'MEMD, MoGLSD, MoH,  MoD, MIA, MWE, PAU,  UNOC, UNBS, NEMA,  Joint Venture Partners'),
(3  ,5  ,2  ,'MEMD, MoGLSD, MoH,  MoD, MoIA, MWE, PAU,  UNOC, UNBS, NEMA,  Joint Venture Partners'),
(3  ,5  ,3  ,'MEMD, MoGLSD, MoH,  MoD, MIA, MWE,  MoLHUD, PAU, UNOC,  UNBS, OPM, NEMA, LGs,  Joint Venture Partners'),
(3  ,5  ,4  ,'MEMD, UNOC, MoGLSD,  MoH, MoD, MIA, MWE,  PAU, UNOC, NEMA, LGs,  Joint Venture Partners'),
(3  ,5  ,5  ,'MEMD, MoGLSD, MoH,  MWE, PAU, UNOC,  NEMA, UWA, LGs, Joint  Venture Partners'),
(3  ,5  ,6  ,'MEMD, UNBS'),
(3  ,6  ,1  ,'MEMD, UNBS, UNOC'),
(3  ,6  ,2  ,'MEMD, MoWT, UNBS'),
(3  ,6  ,3  ,'MEMD, MoWT, UNBS'),
(3  ,6  ,4  ,'UNOC, MoFPED'),
(4  ,1  ,1  ,'UTB, MTWA, LGs,  MoFA, UIA, Private  Sector, Cultural &  Religious Institutions,  UWA, Media/UBC,  MoICT & NG'),
(4  ,1  ,2  ,'MoWT, UNRA,  UCAA, Uganda  Airlines, UTB, CAA'),
(4  ,1  ,3  ,'Uganda Airlines,  Private sector'),
(4  ,1  ,4  ,'Uganda Airlines,  MoFA, MOIA MTIC,  MTWA, UEPB, and  UTB'),
(4  ,2  ,1  ,'MoWT, UNRA,  UCAA'),
(4  ,2  ,2  ,'MLHUD, UWA,  MoWT, Private sector,  MTWA, MWE,  MoFPED, UIA, KCCA'),
(4  ,2  ,3  ,'MTWA, Private sector'),
(4  ,2  ,4  ,'UCC, ICT'),
(4  ,2  ,5  ,'MWE, UWA'),
(4  ,2  ,6  ,'MTIC, UWA, Private  Sector, MTWA,  MOES, MoFPED,  IRA, UEPB, NCS,  MoGLSD'),
(4  ,2  ,7  ,'MoWT, UNRA,  UCAA, Uganda  Airlines, UTB'),
(4  ,3  ,1  ,'MTWA, UWA, LGs,  UTB, MoICT & NG,  MLHUD, MWE),  Cultural & Religious  institutions, UWEC,  MAAIF'),
(4  ,3  ,2  ,'MTWA, UWA, LGs,  UTB, MoICT & NG,  MLHUD, MWE),  Cultural & Religious  institutions, UWEC,  MAAIF'),
(4  ,3  ,3  ,'NULMTWA, OPM, LGs'),
(4  ,3  ,4  ,'UTB, MTWA, MoH,  KCCA, LGs, Tourism  Police, Private Sector,  UWA'),
(4  ,3  ,5  ,'Private Sector,  MTWA, MoFPED,  MTIC, UTB and UWA'),
(4  ,3  ,6  ,'MoDVA'),
(4  ,3  ,7  ,'MTWA, UWA, UPDF,  LGs'),
(4  ,3  ,8  ,'MTWA, UWA, UPDF,  LGs'),
(4  ,3  ,9  ,'UTB, MTWA,  MAAIF, MTIC,  Private Sector, UIA,  UCDA, UWA, UEPB,  MoWT, UNRA,  MoLG, LGs'),
(4  ,4  ,1  ,'UHTTI, UWRTI,  MOES, NCDC'),
(4  ,4  ,2  ,'MTWA, MOES'),
(4  ,4  ,3  ,'MTWA'),
(4  ,4  ,4  ,'MTWA'),
(4  ,4  ,5  ,'MoFPED, MTWA,  MTIC, UTB,  Enterprise Uganda'),
(4  ,4  ,6  ,'MOGLSD, MTWA'),
(4  ,5  ,1  ,'MTWA, UTB'),
(4  ,5  ,2  ,'MoFPED, MTWA,  MTIC, UTB,  Enterprise Uganda,  UDB'),
(4  ,5  ,3  ,'MTWA, UTB'),
(4  ,5  ,4  ,'UTB, MTWA, MoH,  KCCA, LGs, Tourism  Police, Private Sector,  UWA'),
(4  ,5  ,5  ,'OPM, MTWA, LGs,  UWA, UTB, Private   Sector'),
(5  ,1  ,1  ,'MWE, LGs, NEMA,  NFA, MEMD,  MoFA, KCCA, OPM'),
(5  ,1  ,2  ,'MoLG, MWE, LGs,  NEMA, NFA,  MoLHUD, KCCA,  Communities, CSOs,  private sector, DPs,  UWA, Cultural  institutions'),
(5  ,2  ,1  ,'MWE, NEMA, NFA,  MoLG, DLG, UWA,  MLHUD, OPM '),
(5  ,2  ,2  ,'MWE, NEMA,  MoFPED, NPA, UDB'),
(5  ,2  ,3  ,'MEMD, MoFPED'),
(5  ,2  ,4  ,'NFA, MWE, DLG,  CSOs, Private Sector,  Cultural Institutions &  FBOs'),
(5  ,3  ,1  ,'MLHUD, NPA,  MoLG, MTIC, DPs,  PSFU, CSOs, Local  Communities, LGs'),
(5  ,3  ,2  ,'MLHUD, MOLG,  MoJCA'),
(5  ,3  ,3  ,'ULC, MLHUD,  MOLG, KCCA'),
(5  ,3  ,4  ,'MLHUD, MOFPED,  ULC'),
(5  ,3  ,5  ,'MLHUD, MOLG,  ULC, DLBs,  Cultural/Religious  Institutions'),
(5  ,3  ,6  ,'MLHUD, MDA’s,  LGs, Local Communities, Private  Sector, DPs, CSOs'),
(5  ,3  ,7  ,'MoLHUD, MoWT,  MoFPED, MEMD,  UNOC, NITA,  MoLG, MoJICA,  UEDCL, UETCL,  PAU, UNRA, URC,  CAA, URF'),
(5  ,3  ,8  ,'MOLHUD, MOLG,  ULC'),
(5  ,3  ,9  ,'NPA, MLHUD,  MOLG, UBOS,  UNBOS, MUK'),
(5  ,3  ,10 ,'MLHUD, MOLG'),
(5  ,3  ,11 ,'MOLHUD, NPA, all  MDAs, LGs, Private  Sector'),
(5  ,4  ,1  ,'MEMD, MOWT,  NEMA, MoTIC,  MOLHUD, KCCA,  MWE'),
(5  ,4  ,2  ,'MEMD, MoTIC,  Urban Centres,  NEMA '),
(5  ,4  ,3  ,'MWE, MoTIC,  UBOS, UNBS,  MoFPED  NPA, NEMA, CSOs  Academia, DPs,  MOWT'),
(5  ,4  ,4  ,'MWE, MoES,  MoTIC, OPM'),
(5  ,4  ,5  ,'MoTIC, MWE,  UCPC, Academia,  MSTI, UNCST'),
(5  ,5  ,1  ,'MWE, MoLG,  MoFPED, NPA, LGs,  NEMA, NFA, OPM,  KCCA, Communities,  CSOs, private sector,  DPs, UWA'),
(5  ,5  ,2  ,'MWE, MoLG, LGs,  NEMA, NFA,  MoLHUD, UBOS,  Communities, CSOs,  private sector, DPs,  UWA, Cultural  institutions'),
(5  ,5  ,3  ,'MWE, MoWT,  MLHUD, NPA,  MoFPED, MoLG, LG,  All Programme Leads'),
(5  ,5  ,4  ,'MWE (CCD), NFA,  NEMA, MEMD  '),
(5  ,5  ,5  ,'UDB, MWE,  MOFPED, NPA,  Private Sector'),
(5  ,5  ,6  ,'UDB, MWE,  MOFPED, NPA, DPs'),
(5  ,6  ,1  ,'OPM, MoLG, LGs,  MoJCA, Parliament,  Office of the  President, MoFPED,  MoIA, UPF, MoD,  UPDF'),
(5  ,6  ,2  ,'NPA, OPM, UNMA,  UPF, NEMA, MWE,  MAAIF, MEMD,  DLGs, MOH, MoLG,  MoTIC, UPDF,  MoFPED, MoJCA,  MoLHUD, LGs '),
(5  ,6  ,3  ,'OPM, MoFPED,  DLG’s, MAAIF,  MoTIC, MWE, MOH'),
(5  ,6  ,4  ,'OPM, MoLHUD,  MoLG, DLG’s,  MoWT, MoFPED,  MoICT'),
(5  ,6  ,5  ,'UNMA, MICT & NG,  MAAIF, DLG, MoLG  MSTI, OPM'),
(5  ,6  ,6  ,'UNMA'),
(5  ,7  ,1  ,'MoLG, MWE,  MoFPED, LGs, NEMA,  NFA, KCCA,  Communities, CSOs,  private sector, DPs,UWA, Cultural  institutions, MTIC,  MoSTI'),
(5  ,7  ,2  ,'MWE, NEMA, NFA,  MoES, MoICT & NG,  MTWA, CSOs and  Private Sector  Cultural and FBOs'),
(5  ,7  ,3  ,'MWE MSTI,  Academia/research  institutions, NEMA,  NFA, MWE'),
(5  ,7  ,4  ,'NFA, MWE, MTIC,  UIA'),
(5  ,7  ,5  ,'NEMA, MWE, NFA,  MTWA, MAAIF,  MTIC, UDB, MSTI,  UNCST'),
(5  ,7  ,6  ,'MWE'),
(6  ,1  ,1  ,'MoFPED; Parliament; UDB;  Post Bank; Housing Finance;  Pride-Micro Finance;  Microfinance Support Centre'),
(6  ,1  ,2  ,'MoFPED; UDB; UDC;  Parliament; Post Bank; Housing  Finance; Pride-Micro Finance;  Microfinance Support Centre'),
(6  ,1  ,3  ,'MoFPED; MTIC; UDB; USE;  UDC; POST BANK; CMA; UIA,  NPA'),
(6  ,1  ,4  ,'UIA and PSFU, IRA; BOU;  TELECOM COMPANIES;  USE; MOFPED; CMA;  MEMD, MWT, MOFA; MTIC;NSSF; BOU; URBRA; MoJCA;  LGs'),
(6  ,2  ,1  ,'MTIC & UIA; ENTERPRISE  UGANDA; PSFU;  MICROFINANCE SUPPORT  CENTRE; UMA; UDB;  USSIA; LGs, Farmers’  associations/cooperatives'),
(6  ,2  ,2  ,'MTIC; UIRI; MOSTI; UNCSI;  EPRC; URSB; LGs, Academia,  Private Sector, PSFU, UIA'),
(6  ,3  ,1  ,'MoFPED; MOTIC; MOGLSD;  PPDA; UNBS; MEMD; LGs'),
(6  ,3  ,2  ,'MoWT; MOTIC; MOGLSD;  PPDA; UNBS; MEMD; LGs'),
(6  ,3  ,3  ,'MoFPED, MoWT, UDC, NPA'),
(6  ,3  ,4  ,'MoFPED; MOTIC; UIA'),
(6  ,4  ,1  ,'MoFPED, MOTIC, UDC, UIA,  UFZA'),
(6  ,4  ,2  ,'MoSTI, UNCST, UIRI,  Academia, NPA, Private sector'),
(6  ,4  ,3  ,'MoFPED, MoTIC, MoFA'),
(6  ,5  ,1  ,'MTIC, MFPED, UNBS,  Development Partners'),
(6  ,5  ,2  ,'MTIC, UIA, UNBS, PSFU,  UMA, URSB'),
(6  ,5  ,3  ,'PARLIAMENT, PPDA, UIA,  MOJCA, UDB, UDC'),
(6  ,5  ,4  ,'UBOS, PSFU, NPA, MoFPED'),
(6  ,5  ,5  ,'MOFPED, MWE, MTIC, NPA,  PSFU, UDC, UMA, MoLG, LG'),
(6  ,5  ,6  ,'UIA, MoFPED, MTIC, UMA'),
(6  ,5  ,7  ,'UFZA, MTIC, UEPB, UMA,  MoFPED'),
(7  ,1  ,1  ,'MTIC, MFPED, MoWT,  MEMD, MoWE, MAAIF,  MICT&NG, UIA, UFZA,  UIRI, NEMA, LGs  Development Partners'),
(7  ,1  ,2  ,'MTIC, MFPED, UDB, MWE'),
(7  ,1  ,3  ,'MTIC, MFPED, MoWT,  MEMD, MoWE,  Development Partners'),
(7  ,1  ,4  ,'MTIC, MFPED, MoWT,'),
(7  ,1  ,5  ,'MTIC, MWE, UIRI, NEMA'),
(7  ,2  ,1  ,'MoH, Medical related  manufacturers, Academic &  research institutions, Health  Workers’ Professional  Associations, NCRI,  International Health Agencies'),
(7  ,2  ,2  ,'MTIC, UNBS, UMA, UDB,  Private sector'),
(7  ,2  ,3  ,'MTIC, MOSTI, UIA,  Academia, Private sector'),
(7  ,2  ,4  ,'MTIC, UMA, UDB, Private  sector'),
(7  ,3  ,1  ,'MTIC, MoFA, UNBS, UEPB,'),
(7  ,3  ,2  ,'MTIC, MFPED, URA, UMA'),
(7  ,3  ,3  ,'MTIC, MFPED, URA, UEPB,  UMA'),
(7  ,3  ,4  ,'MTIC, MFPED, URA, UEPB,  UMA, Development Partners,'),
(7  ,3  ,5  ,'MTIC, MoFA, URA, UMA,  UEPB, Development Partners'),
(7  ,3  ,6  ,'MTIC, MoFA, MoJCA,  Cabinet, Parliament '),
(7  ,3  ,7  ,'MTIC, MoFA, UEPB,'),
(7  ,3  ,8  ,'MTIC, MFPED, UNBS,  Development Partners '),
(7  ,3  ,9  ,'MTIC, MoFA, UEPB'),
(7  ,4  ,1  ,'MTIC, MoJCA, Cabinet,  Parliament '),
(7  ,4  ,2  ,'MTIC, MoIA, UNBS, UPF'),
(7  ,4  ,3  ,'MTIC, MoJCA, URA,  Cabinet, Parliament, UMA'),
(7  ,4  ,4  ,'MWE, MTIC, UNBS, UIA'),
(8  ,1  ,1  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, LGs, UNRA, URC,  CAA, URF,'),
(8  ,1  ,2  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, LGs, MoJCA, UNRA, URC,  CAA, URF,'),
(8  ,1  ,3  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,1  ,4  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,1  ,5  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,1  ,6  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,2  ,1  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,2  ,2  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF'),
(8  ,2  ,3  ,'URA, UNRA, UPF, URC, CAA'),
(8  ,2  ,4  ,'MoWT, UNRA, URC, CAA, '),
(8  ,2  ,5  ,'MoFPED, & MoWT'),
(8  ,2  ,6  ,'MoWT, UNRA, URC, CAA, MoICT,  NITA'),
(8  ,3  ,1  ,'MoWT, MoFPED, MEMD,  MoLHUD, UNOC, NITA, MoLG,  MoJCA, UEDCL, UETCL, PAU  UNRA, URC, CAA, URF'),
(8  ,3  ,2  ,'UNRA, URC, CAA, URF, MoFPED,  MoWT, MoLG'),
(8  ,3  ,3  ,'MoWT, MLHUD, UNRA, URC,  CAA, URF'),
(8  ,3  ,4  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,4  ,1  ,'MoWT, UNRA, URC, CAA, '),
(8  ,4  ,2  ,'MoWT,UNRA, URC, CAA, '),
(8  ,4  ,3  ,'UNRA, URC, CAA, URF, MoFPED,  MoWT, MoLHUD, PPDA, MoLG,  MoJCA'),
(8  ,5  ,1  ,'MoWT'),
(8  ,5  ,2  ,'MoWT, MoLG, MoLHUD, UPF,  UNRA, CAA, URC,'),
(8  ,5  ,3  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF'),
(8  ,5  ,4  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,5  ,5  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF, UAC, MoGLSD, LGs'),
(8  ,6  ,1  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,6  ,2  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,6  ,3  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,6  ,4  ,'MoWT, MoFPED, MoLHUD, PPDA,  MoLG, MoJCA, UNRA, URC, CAA,  URF,'),
(8  ,6  ,5  ,'MoWT, UNRA, URC'),
(9  ,1  ,1  ,'MEMD, UETCL, LGs'),
(9  ,1  ,2  ,'MEMD, UETCL, MOLHUD,  UIA, UFZA, UMA, ERA,  MOFPED, DPs'),
(9  ,1  ,3  ,'MEMD, UETCL, MoFPED,  MoFA'),
(9  ,1  ,4  ,'UEDCL, UMEME, MEMD,  ERA, REA, MOLHUD, LGs,  DPs, MPFPED'),
(9  ,1  ,5  ,'ERA, MEMD, LGs, DPs,  UEDCL, MOFPED'),
(9  ,1  ,6  ,'ERA, MOFED, '),
(9  ,1  ,7  ,'MoICT, MoSTI, REA,  MEMD'),
(9  ,1  ,8  ,'UNBS UNBS, MEMD,  ERA, UEGCL, UEDCL,  UETCL, REA, PSFU'),
(9  ,1  ,9  ,'ERA, MEMD, UEGCL,  UETCL, UEDCL, REA'),
(9  ,2  ,1  ,'UEGCL, ERA, MEMD,  MOLHUD, MOFPED, DPs,  MWE, NEMA'),
(9  ,2  ,2  ,'UEGCL, ERA, MEMD,  MOFPED, MWE, UWA,  NEMA'),
(9  ,2  ,3  ,'MEMD'),
(9  ,3  ,1  ,'ERA, MEMD, LGs, DPs,  UEDCL, MOFPED'),
(9  ,3  ,2  ,'MEMD, ERA, CSOS,  LGs, MOFPED, MoH,  MAAIF, MoES'),
(9  ,3  ,3  ,'MEMD, CSOs, MoWT,  MoH'),
(9  ,3  ,4  ,'ERA. MEMD, PSFU,  UETCL, UEDCL'),
(9  ,3  ,5  ,'MEMD'),
(9  ,4  ,1  ,'MEMD, ERA, CSOS,  LGs, MOFPED, MoH,  MAAIF, MoES, UECCC'),
(9  ,4  ,2  ,'MEMD, UNOC'),
(9  ,4  ,3  ,'MEMD, ERA, LGS,  CSOs, DPs'),
(9  ,4  ,4  ,'UNBS, MEMD, ERA,  UEGCL, UEDCL,  UETCL, REA, PSFU'),
(10 ,1  ,1  ,'MoICT&NG, NITAU,  UCC, POSTA, UTL,  MEMD, UETCL,  UEDCL, UBC/SIGNET,  Other Utility service  providers (MoWE,  MoWT),  Communication service  providers'),
(10 ,1  ,2  ,'MoICT&NG, NITAU,  UCC, UBC/SIGNET,  Broadcast service  providers'),
(10 ,1  ,3  ,'NITA, MoICT & NG,  UCC, Private Sector  players'),
(10 ,2  ,1  ,'ALL MDAs'),
(10 ,2  ,2  ,'MoICT&NG, NITAU,  UCC, Private Sector  players, Security  agencies'),
(10 ,2  ,3  ,'MoICT&NG, NITAU,  UCC, Private Sector'),
(10 ,2  ,4  ,'POSTA, MoICT & NG,  NITAU, MoPS'),
(10 ,2  ,5  ,'ALL MDAs, Private  Sector'),
(10 ,2  ,6  ,'POSTA, MoICT & NG,  NITAU, MOLG, LGs,  KCCA'),
(10 ,3  ,1  ,'MoICT & NG, UICT,  MSTI, UCC, NITAU,  ACADEMIA, PRIVATE  SECTOR'),
(10 ,3  ,2  ,'MoICT & NG, UICT,  MSTI, PRIVATE  SECTOR, CIVIL  SOCIETY, ACADEMIA'),
(10 ,3  ,3  ,'MoICT&NG, NITAU,  UCC, PRIVATE  SECTOR, ACADEMIA'),
(10 ,3  ,4  ,'MoICT & NG, UCC,  NITA, MSTI, PRIVATE  SECTOR'),
(10 ,3  ,5  ,'MoICT&NG, NITAU,  UCC, PRIVATE  SECTOR, ACADEMIA,  NEMA, MWE, LGs'),
(10 ,4  ,1  ,'MoICT & NG, UICT,  MoES, NCDC, NCHE,  ACADEMIA'),
(10 ,4  ,2  ,'MoICT & NG, UICT,  NITA, MoES, NCDC,  NCHE'),
(10 ,4  ,3  ,'MoICT & NG, UICT,  UCC, NITA, NCHE  ACADEMIA'),
(10 ,4  ,4  ,'MoICT & NG, UICT,  UCC, MoES, NCHE'),
(10 ,4  ,5  ,'MoICT & NG, UICT,  UCC, NITA, MoES,  NCDC, NCHE,  ACADEMIA'),
(10 ,4  ,6  ,'MoICT & NG, UICT,  MoES, NITAU, NCHE'),
(10 ,5  ,1  ,'MoICT & NG, UCC,  NITAU'),
(10 ,5  ,2  ,'MoICT & NG, UCC,  NITAU'),
(11 ,1  ,1  ,'MLHUD, MoLG, NPA, MDA’s,  Private sector, DPs'),
(11 ,1  ,2  ,'MGLSD, MoFPED, MOE,  MLHUD, MOLG'),
(11 ,1  ,3  ,'MOTIC, URA, MoFPED,  MoLHUD MoLG, Private Sector'),
(11 ,1  ,4  ,'MoWT, KCCA, MLHUD,  MDA’s, pr ivate sector, DPs,  CSOs, Local Communities, LGs'),
(11 ,1  ,5  ,'MoWE, KCCA, MLHUD, MoLG,  MoWT, NWSC, MDA’s, private  sector, DPs, CSOs, Local  Communities'),
(11 ,1  ,6  ,'MoWE, KCCA, MLHUD, MoLG,  MoWT, MoH, MoES, NEMA,  private sector, DPs, CSOs, Local  Communities'),
(11 ,2  ,1  ,'MLHUD, MoLG, MoFPED, NPA,  MDAs, MTIC'),
(11 ,2  ,2  ,'MLHUD, MoLG, MoFPED, NPA,  MDAs, MTIC, MoWT'),
(11 ,2  ,3  ,'MOFPED, MKCC&MA,  MLHUD, NPA, DPs, Private  Sector, Civil Society, Local  Communities'),
(11 ,2  ,4  ,'UIA, MLHUD, Private sector'),
(11 ,2  ,5  ,'UIA, MTIC, Uganda Free zones  Authority, MoWT, MoLG,  MLHUD, MAAIF, LGs'),
(11 ,2  ,6  ,'UNHCC, MLHUD, MOLG,  MKCC&MA, Housing Finance  Bank'),
(11 ,2  ,7  ,'MTIC, MLHUD, Private Sector '),
(11 ,3  ,1  ,'MLHUD, MWE, NEMA Private  Sector'),
(11 ,3  ,2  ,'MLGSD, MOWE, MOEMD,  MLHUD'),
(11 ,3  ,3  ,'MLHUD, MOFPED, OPM,  MOEMD, MKCC&MA'),
(11 ,3  ,4  ,'MOW, MLHUD, MOWE'),
(11 ,3  ,5  ,'MLHUD, MOWT, MOWE, OPM'),
(11 ,3  ,6  ,'MLHUD, NEMA, MOWE'),
(11 ,3  ,7  ,'MLHUD, MOWE'),
(11 ,4  ,1  ,'MLHUD, MOLG, OTHER MDAs  and Private Sector'),
(11 ,4  ,2  ,'MKCC&MA, MLHUD, MOLG,  other MDAs and Private Sector'),
(11 ,5  ,1  ,'MLHUD, MWE, PSFU, CSOs,  Local Communities, MoLG, LGs'),
(11 ,5  ,2  ,'MLHUD, KCCA, MWE, MoLG,  PSFU, CSOs, Local Communities,  LGs'),
(11 ,5  ,3  ,'MLHUD, NPA, MoLG, MTIC,  DPs, PSFU, CSOs, Local  Communities, LGs'),
(12 ,1  ,1  ,'MoES, MoGLSD,  MoFPED, MoLG, Private  Sector, DPs'),
(12 ,1  ,2  ,'MoH, MoES, MoGLSD,  MTIC, MoFPED, MoLG,  MAAIF, Private Sector (eg  Maama Care Foundation),  DPs'),
(12 ,1  ,3  ,'MOH, MoGLSD'),
(12 ,1  ,4  ,'MOH, MoGLSD, Private  Sector, CSOs'),
(12 ,1  ,5  ,'MoGLSD, MoJCA, MoIA,  MoFPED, MoLG, Private  Sector, CSOs'),
(12 ,1  ,6  ,'MoES, MoH, MoGLSD,  MoFPED, MoLG, NCHE,  MoWE, Private Sector,  DPs'),
(12 ,1  ,7  ,'MoES, MoLG, LGs,  Private Sector, CSOs'),
(12 ,1  ,8  ,'MoES, MoICT&NG,  MoLG, MoFPED'),
(12 ,1  ,9  ,'MOES, MoICT&NG,  Telecom companies,  HEI’s, ICT Entrepreneurs,  LGs'),
(12 ,1  ,10 ,'MoES, NITA-U, LGs,  UBOS'),
(12 ,1  ,11 ,'MoES, NCDC, MoLG'),
(12 ,1  ,12 ,'MOH, MoES, MGLSD,  MoLG, LGs, NPC, NPA'),
(12 ,2  ,1  ,'MoGLSD, MoES, UMA,  PSFU, MTIC, MoLG,  NCHE, UBOS'),
(12 ,2  ,2  ,'MoES, UMA, PSFU,  MTIC, MoGLSD, DIT,  IndustryL'),
(12 ,2  ,3  ,'MoES, Training  Institutions, Accreditation  bodies, Industry'),
(12 ,2  ,4  ,'MoES, MoTIC, MoGLSD,  NCHE, UMA, PSFU,  industry'),
(12 ,2  ,5  ,'MoPS, MOFPED, MOES,  NCHE'),
(12 ,2  ,6  ,'MOES, LGs, MGLSD'),
(12 ,2  ,7  ,'MoPS, MoES, MoFPED,  NCHE, MoGLSD, MTIC,  DIT, UMA, PSFU, MoFA,  MoIA, NPA, Tertiary  Institutions, HESFEB,  Industry'),
(12 ,2  ,8  ,'MoES, MoFPED, NCHE,  Universities'),
(12 ,2  ,9  ,'MoES, MoFPED, Industry'),
(12 ,2  ,10 ,'NPA, MoPS, MoGLSD,  Sectors and LGs, MoES,  MoFPED, NCHE,  Universities'),
(12 ,2  ,11 ,'NCDC, MoES'),
(12 ,3  ,1  ,'MoES, MoSTI, MoFPED,  MoLG, NCDC'),
(12 ,3  ,2  ,'MoES, MoFPED, MoSTI'),
(12 ,3  ,3  ,'MoES, UNEB, NCDC,  MoSTI'),
(12 ,3  ,4  ,'MoES, MoSTI, Private  sector, UMA, HESFEB,  NCHE, HEIs, Universities,  Industry'),
(12 ,3  ,5  ,'MoES, MoSTI,  Universities, NCHE'),
(12 ,4  ,1  ,'MoH, UCI, UHI, MoES,  MoGLSD, MoLG,  MoW&T, MoPS, Private  Sector, CSOs,  HDPs, OPM, UAC,  Cultural and Religious  Institutions'),
(12 ,4  ,2  ,'MoH, UCI, UHI, MoES,  MoGLSD, MoLG,  MoW&T, MoPS, Private  Sector, CSOs,  HDPs, OPM, UAC, LGs,  Community, Cultural and  Religious Institutions'),
(12 ,4  ,3  ,'MoFPED, MoH, MoLG,  MoPS, MoICT&NG, NPC,  NMS / JMS, Professional  Councils, Professional  Associations, Medical  Bureaus, Private Health  Providers, HDP'),
(12 ,4  ,4  ,'MoH, UCI, UHI, MoES,  MoGLSD, MoLG,  MoW&T, MoPS, Private  Sector, CSOs,  HDPs, OPM, UAC, LGs,  Community, Cultural and  Religious Institutions'),
(12 ,4  ,5  ,'MWE, OPM, MoH,  MoLG, MoW&T,  MoGLSD, MoES, MEMD,  MoIA, Medical Bureaus,  Private Health Providers,  HDP'),
(12 ,4  ,6  ,'MoH, MWE, NPC, MoLG,  MoGLSD, Private Sector,  CSOs, HDPs, Community,  Religious leaders, DPs'),
(12 ,4  ,7  ,'MOH, Parliament,  MoFPED'),
(12 ,4  ,8  ,'MOH, Research &  academic Institutions,  Health MDAs, MSTI,  Private sector'),
(12 ,4  ,9  ,'OPM, MoH, MoLG,  MWE, MoW&T,  MoGLSD, MoES, MEMD,  MoIA, Medical Bureaus,  Private Health Providers,  HDP'),
(12 ,4  ,10 ,'OPM, MoH, MoLG,  MAAIF, MWE, MoGLSD,  MoES'),
(12 ,4  ,11 ,'MoGLSD, MoH, MoLG,  MoW&T, MoGLSD,  MoES, MoIA'),
(12 ,4  ,12 ,'MoH, MoES, MoGLSD,  MoLG, LGs'),
(12 ,4  ,13 ,'MoH, MoLG, MoW&T,  MoGLSD, MoES'),
(12 ,4  ,14 ,'MFPED, NPC, NPA,  UBOS, NIRA, URSB,  MoIAs, MoDVA, MoLGs'),
(12 ,4  ,15 ,'OPM, MoH, MoLG,  MWE, MoGLSD, MoES,  MAAIF, MoFPED, NDA,  MTIC, Private Sector,  Host LG, Development  Partners'),
(12 ,4  ,16 ,'UAC, MoH, All MDAs,  Civil Society, Private  Sector, Development  Partners'),
(12 ,5  ,1  ,'MoGLSD, OPM'),
(12 ,5  ,2  ,'MoGLSD, UNMA, OPM,  MoFPED, NEMA, MoH,  LGs'),
(12 ,5  ,3  ,'MoGLSD, MoLG'),
(12 ,5  ,4  ,'MoGLSD, MoFPED,  URBRA'),
(12 ,5  ,5  ,'MoGLSD, MoES, MoLG,  LGs, DPs, CSOs'),
(12 ,5  ,6  ,'MoGLSD, MoES,  MoFPED, LGs, NPC, DPs,  CSOs, UPF, Judiciary,  MoJCA'),
(12 ,5  ,7  ,'MoGLSD, EOC,  MoFPED, LGs, NPC, DPs,  CSOs'),
(12 ,5  ,8  ,'MoGLSD, MoH, MoES,  MoLG, LGs'),
(12 ,5  ,9  ,'MGLSD, CSOs, Private  Sector, LGs, All MDAs'),
(12 ,5  ,10 ,'MGLSD, CSOs, Private  Sector, LGs,'),
(12 ,6  ,1  ,'MoES, MoGLSD, MoLG,  NCS, Sports Clubs'),
(12 ,6  ,2  ,'MoES, NCDC, NCS,  MoLG, Universities'),
(12 ,6  ,3  ,'MoES, MoFPED, NCS,  Sports Clubs'),
(12 ,6  ,4  ,'MoES, MoFPED, NCS,  Sports Clubs &  Associations, FUFA,  Private Sector'),
(12 ,6  ,5  ,'Private sector, MoES,  MoFPED, NCS, Sports  Clubs'),
(12 ,6  ,6  ,'MoES, MoFPED, NCS,  Sports Clubs'),
(13 ,1  ,1  ,'MoSTI, MFPED,  MLHUD, LGs, Private  Sector, DPs'),
(13 ,1  ,2  ,'MoSTI, MFPED,  MLHUD, MTIC, LGs,  Private Sector, UMA,  DPs'),
(13 ,1  ,3  ,'MoSTI, MFPED,  MLHUD, MTIC, MoES,  LGs, Private Sector, DPs'),
(13 ,1  ,4  ,'MoSTI'),
(13 ,1  ,5  ,'MoSTI, MoH, MAAIF,  UVRI, UMA, Research  Institutions, Academia,  Private Sector, DPs'),
(13 ,1  ,6  ,'MoSTI, MoH, MAAIF'),
(13 ,1  ,7  ,'MoSTI, MFPED'),
(13 ,2  ,1  ,'MoSTI'),
(13 ,2  ,2  ,'MoSTI, MoES, NCDC,  NCHE, Academia,  Private Sector, DPs'),
(13 ,2  ,3  ,'MoSTI, MoES, NCHE,  Academia, Private  Sector, DPs'),
(13 ,2  ,4  ,'MoSTI, MEMD, MoH,  MAAIF, MFPED,  NCHE NPA, Academia,  Private Sector, All  MDAs, DPs'),
(13 ,2  ,5  ,'MoSTI'),
(13 ,3  ,1  ,'MoSTI, MoICT&NG,  MoH, MAAIF, MTIC,  NPA, EPRC, Academia,  Private Sector, DPs'),
(13 ,3  ,2  ,'MoSTI, MoICT&NG,  MoH, MAAIF, LGs,  UIRI, UNCST, UMA,  Private Sector, DPs'),
(13 ,3  ,3  ,'MoSTI, MoICT&NG,  MoH, MJCA, MAAIF,  MoIA LGs, URSB'),
(13 ,3  ,4  ,'MoSTI, MoICT&NG,  MFPED, MoH, MAAIF,  UBoS, NPA, All MDAs,  Private Sector, DPs'),
(13 ,3  ,5  ,'MoSTI, MEMD, MoH,  MAAIF, MoWT,MFPED, NARO,  NaGRIC, Academia,  Private Sector, DPs'),
(13 ,3  ,6  ,'MoSTI, MEMD, MoH,  MAAIF, MoWT,  MFPED, NARO,  NaGRIC, Academia,  Private Sector, DPs'),
(13 ,3  ,7  ,'MoSTI, MEMD, MoH,  MAAIF, MFPED, NPA,  Academia, Private  Sector, All Sectors, DPs'),
(13 ,3  ,8  ,'MoSTI'),
(13 ,3  ,9  ,'MoSTI, OPM'),
(13 ,3  ,10 ,'MoSTI, MAAIF, MoH,  MICT'),
(13 ,4  ,1  ,'MoSTI, MoICT&NG,  NITA-U'),
(13 ,4  ,2  ,'MoSTI, Academia,  Private Sector, All  Sectors, DPs'),
(13 ,4  ,3  ,'MoSTI, MTIC, UNBS,  Private Sector'),
(13 ,4  ,4  ,'MoSTI, NPA, UMA,  Universities'),
(13 ,4  ,5  ,'MoSTI, MoFPED,  MTIC'),
(13 ,4  ,6  ,'MoSTI'),
(13 ,5  ,1  ,'MoSTI, MoFA'),
(13 ,5  ,2  ,'MoSTI, MoICT&NG,  MoJCT, Parliament,  Cabinet Secretariat'),
(13 ,5  ,3  ,'MoSTI, MoJCT,  Parliament, Cabinet  Secretariat'),
(13 ,5  ,4  ,'MoSTI, MoFA'),
(14 ,1  ,1  ,'OP, MOGLSD, ICT&NG,  UBC, MoLG, Uganda  Media Centre, GCIC'),
(14 ,1  ,2  ,'MOGLSD, JSC, ICT&NG,  UHRC, EC, OP, MoLG,  LGs'),
(14 ,1  ,3  ,'MOGLSD, UBC, OP,  MoLG'),
(14 ,1  ,4  ,'MOGLSD, MOFA'),
(14 ,1  ,5  ,'National Women Councils,  Local Council women  Leaders, MOGLSD,  MoLG, Youth councils,  PWD Councils, CSOs'),
(14 ,2  ,1  ,'MOGLSD, MoLG, OP,  LGs, Religious and  Cultural institutions and  other Non-State Actors'),
(14 ,2  ,2  ,'MOGLSD, LGs, OP,  MoLG'),
(14 ,2  ,3  ,'MOGLSD, LGs, OP,  MoLG, Religious and  Cultural institutions and  other Non-State Actors'),
(14 ,3  ,1  ,'MOGLSD, MOPS, UCSC,MOES,  MODVA, MoLG, MoICT&NG'),
(14 ,3  ,2  ,'MoICT&NG, MOGLSD,  NPA, UBC, MoLG'),
(14 ,3  ,3  ,'MoPS, OP (Ethics &  Integrity), MoLG'),
(14 ,3  ,4  ,'MoGLSD, MoLG, OP  (Ethics & Integrity)'),
(14 ,3  ,5  ,'LGs, MoGLSD, MoLG,  OP (Ethics & Integrity),  MoJCA, UPF'),
(14 ,4  ,1  ,'MOGLSD, MoLG, NPC,  JLOS, LGs, OP, DPs,  UBC, Religious and  Cultural institutions and  other Non-State Actors'),
(14 ,4  ,2  ,'OPM, MOGLSD, MoLG,  LGs, MOH, OP, MOES,  MoICT&NG, MOGLSD,  MOWE, MoLG, LGs,  Non-State Actors, DPs'),
(15 ,1  ,1  ,'MODVA, ISO, ESO,  MoIA, UPF, UPS'),
(15 ,1  ,2  ,'MODVA, ISO, ESO,  MIA, UPF, UPS'),
(15 ,1  ,3  ,'MODVA, MoIA, UPF'),
(15 ,1  ,4  ,'MODVA, ISO, ESO,  MoIA, MoSTI, '),
(15 ,1  ,5  ,'MODVA'),
(15 ,1  ,6  ,'MoIA, UPF'),
(15 ,1  ,7  ,'NIRA, DCIC'),
(15 ,1  ,8  ,'MODVA, MoIA, DCIC,  UPF, MoH, LGs'),
(15 ,1  ,9  ,'MODVA, MoIA, DCIC,  UPF'),
(15 ,1  ,10 ,'MODVA, MoIA, DCIC,  UPF, OP, MoH, LGs'),
(15 ,1  ,11 ,'MoIA, DCIC, MODVA,  UPF, OP, LGs'),
(15 ,1  ,12 ,'MoIA, DCIC, MODVA,  UPF, OP'),
(15 ,2  ,1  ,'Parliament, MDAs'),
(15 ,2  ,2  ,'MoDVA, OP, MoIA,  MoJCA, UPF, ULRC'),
(15 ,2  ,3  ,'Parliament, ULRC,  MDAs, DEI'),
(15 ,2  ,4  ,'Parliament, LGs'),
(15 ,3  ,1  ,'Parliament, MoJCA  Institutions, MoDVA'),
(15 ,3  ,2  ,'MoJCA, Judiciary,  ULRC, UHRC, DGAL,  LDC, UPS, UPF'),
(15 ,3  ,3  ,'MoJCA, LG courts'),
(15 ,3  ,4  ,'UPF, MoLG, LGs'),
(15 ,3  ,5  ,'UPF, UPS, Judiciary,  MoJCA'),
(15 ,3  ,6  ,'NIRA, MoIA, DCIC,  URSB, LGs'),
(15 ,4  ,1  ,'MoJCA, MoIA, URSB,  DCIC, MOICT & NG,  NITA-U, UPS, Judiciary'),
(15 ,5  ,1  ,'Parliament'),
(15 ,5  ,2  ,'Citizenry, URA, OPM  (Barazas), MDAS, LGs'),
(15 ,5  ,3  ,'IG, OAG, DEI, PPDA,  FIA, JLOS institutions,  Media, CSOs'),
(15 ,5  ,4  ,'OAG, MoFPED,  Parliament'),
(15 ,5  ,5  ,'DEI, IG, OP, UPF,  Judiciary, MoJCA'),
(15 ,5  ,6  ,'Anti-corruption  institutions, NPA,  MDAs, LGs, MOFPED'),
(15 ,6  ,1  ,'EC, Parliament, CSOs,  UHRC'),
(15 ,6  ,2  ,'Parliament, LGs'),
(15 ,7  ,1  ,'UHRC, DPs, OPM, NPA,  UPF, MoGLSD'),
(15 ,7  ,2  ,'NPA, UHRC'),
(15 ,8  ,1  ,'OPM, MoLG, LGs, DPs'),
(15 ,8  ,2  ,'OPM, MoLG, LGs'),
(15 ,8  ,3  ,'OPM, MoLG'),
(16 ,1  ,1  ,'OP, OPM, MoPS'),
(16 ,1  ,2  ,'MoPS, OPM, NPA'),
(16 ,1  ,3  ,'MoPS, OP, OPM,  MoFPED, NPA'),
(16 ,1  ,4  ,'OP, OPM, MoLG'),
(16 ,2  ,1  ,'OP; MoPS; OPM;  MoFPED; NPA; '),
(16 ,2  ,2  ,'MoPS, OPM, MoLG'),
(16 ,2  ,3  ,'OPM, MoPS, MoLG,  MoFPED, NPA'),
(16 ,3  ,1  ,'MoPS, OP; OPM; UPDF;  NPA, LGs '),
(16 ,3  ,2  ,'MoPS, OP; OPM; IGG;  MoFPED'),
(16 ,3  ,3  ,'MoPS, OPM, MoFPED,  MoLG'),
(16 ,3  ,4  ,'MoPS, MoFPED, MoLG'),
(16 ,3  ,5  ,'MoPS'),
(16 ,3  ,6  ,'MoPS, MoFPED, MoJCA,  Parliament'),
(16 ,3  ,7  ,'MoPS, MoE, NCHE,  tertiary institutions'),
(16 ,4  ,1  ,'OP, MoLG, MoFPED,  LGs, PSFU, DPs'),
(16 ,4  ,2  ,'MoFPED, NPA, MoLG,  LGs'),
(16 ,4  ,3  ,'MOLG, OPM, OP, LGs,  UBC, NPA'),
(16 ,4  ,4  ,'MoPPED, MoLG, LGFC,  NPA, OP, OPM, URA,  LGs'),
(16 ,5  ,1  ,'MoICT&NG; NITA-U;  MoPS, UBC '),
(16 ,5  ,2  ,'MoICT&NG, NIRA,  NITA, OP, OPM, URA,  MoH, MoES, Security  Agencies, UBC'),
(16 ,5  ,3  ,'MoICT&NG, Uganda  Media Centre, UBC, UCC,  GCIC'),
(17 ,1  ,1  ,'LGs, MGLD,  Farmers groupings'),
(17 ,1  ,2  ,'MAAIF'),
(17 ,1  ,3  ,'MWE, MAAIF'),
(17 ,1  ,4  ,'LGs, CSOs, Farmers  grouping'),
(17 ,1  ,5  ,'NARO, OWC,  Cooperatives'),
(17 ,1  ,6  ,'MAAIF, MFPED'),
(17 ,1  ,7  ,'UIA. OWC'),
(17 ,1  ,8  ,'MTIC, MAAIF'),
(17 ,1  ,9  ,'MAAIF'),
(17 ,1  ,10 ,'MTIC, MAAIF'),
(17 ,1  ,11 ,'LGs, OPM, DPs'),
(17 ,2  ,1  ,'LGs'),
(17 ,2  ,2  ,'MoWT, MOLG,  UNRA, LGs'),
(17 ,2  ,3  ,'MEMD, MOLG,  REA, LGs'),
(17 ,2  ,4  ,'MO ICT&NG, NITA'),
(17 ,3  ,1  ,'NPA, MoLG, LGs'),
(17 ,3  ,2  ,'MTWA, UTB'),
(17 ,3  ,3  ,'MTWA, UTB'),
(17 ,3  ,4  ,'MTWA, UTB'),
(17 ,3  ,5  ,'MTWA, UTB'),
(17 ,3  ,6  ,'MTWA, UTB'),
(17 ,3  ,7  ,'MTWA, UTB'),
(17 ,3  ,8  ,'MEMD'),
(17 ,3  ,9  ,'MEMD'),
(17 ,3  ,10 ,'MEMD'),
(17 ,3  ,11 ,'MFPED, MTIC'),
(17 ,3  ,12 ,'MTW, UNRA'),
(17 ,3  ,13 ,'MEMD'),
(17 ,3  ,14 ,'MWE'),
(17 ,3  ,15 ,'MEMD'),
(17 ,3  ,16 ,'MWE, NEMA'),
(17 ,3  ,17 ,'?'),
(17 ,3  ,18 ,'MWE'),
(17 ,4  ,1  ,'MOLG'),
(17 ,4  ,2  ,'MOLG'),
(18 ,1  ,1  ,'MOFPED, NPA,  NPC, NIRA,  MoLHUD, UBOS'),
(18 ,1  ,2  ,'MOLG, MOPS'),
(18 ,1  ,3  ,'MOGLSD, NPA,  UBOS'),
(18 ,1  ,4  ,'OPM, OP,  MOFPED, NPA,  MoLG, Universities'),
(18 ,2  ,1  ,'MOFPED, URA,  NIRA, MOICT'),
(18 ,2  ,2  ,'MOFPED'),
(18 ,2  ,3  ,'MOFPED'),
(18 ,2  ,4  ,'MOFPED, URA,  URSB'),
(18 ,2  ,5  ,'URA, MOLG, LG'),
(18 ,2  ,6  ,'MOFPED, URA'),
(18 ,2  ,7  ,'MOFPED'),
(18 ,2  ,8  ,'Parliament,  MOFPED, NPA'),
(18 ,2  ,9  ,'MOFPED'),
(18 ,2  ,10 ,'MOFPED, OAG'),
(18 ,2  ,11 ,'MOFPED, MOPS,  MOWT, MOLG'),
(18 ,2  ,12 ,'Parliament,  MOFPED, NPA,  Sectors, MOLG'),
(18 ,2  ,13 ,'MOFPED, NPA,  Sectors, MOLG,'),
(18 ,2  ,14 ,'MoFPED, PPDA,'),
(18 ,2  ,15 ,'Parliament,  MOFPED,'),
(18 ,2  ,16 ,'MoFPED, AGO,'),
(18 ,2  ,17 ,'MoFPED,'),
(18 ,2  ,18 ,'MoFPED, PPDA,  Parliament'),
(18 ,2  ,19 ,'MoFPED, NPA,  Research organs'),
(18 ,3  ,1  ,'MoPS, MoLG,  MoGLSD,'),
(18 ,3  ,2  ,'MoFPED, MoLG'),
(18 ,3  ,3  ,'MoFPED, LGFC,  NPA'),
(18 ,3  ,4  ,'OPM, NPA'),
(18 ,3  ,5  ,'MoLG, LGs'),
(18 ,4  ,1  ,'OP, OPM,  MoFPED, NPA'),
(18 ,4  ,2  ,'MoFPED,  Parliament'),
(18 ,4  ,3  ,'NPA, OPM'),
(18 ,4  ,4  ,'OPM, NPA, UBOS'),
(18 ,4  ,5  ,'MoFPED, NPA'),
(18 ,4  ,6  ,'OAG'),
(18 ,4  ,7  ,'MoFPED, NPA'),
(18 ,5  ,1  ,'NPA, UBOS'),
(18 ,5  ,2  ,'UBOS'),
(18 ,5  ,3  ,'UBOS'),
(18 ,5  ,4  ,'UBOS'),
(18 ,5  ,5  ,'UBOS'),
(18 ,5  ,6  ,'UBOS'),
(18 ,5  ,7  ,'UBOS'),
(18 ,5  ,8  ,'UBOS'),
(18 ,5  ,9  ,'UBOS'),
(18 ,5  ,10 ,'UBOS'),
(18 ,5  ,11 ,'UBOS, NIRA, LGs'),
(18 ,6  ,1  ,'NPA, OP, OPM,  MoSTI, MoFPED,  Academia, CSOs,Religious Entities,  Cultural Institutions'),
(18 ,6  ,2  ,'MOFPED, OAG'),
(18 ,6  ,3  ,'MFPED, OAG'),
(18 ,6  ,4  ,'OP, OPM,  Parliament, NPA'),
(18 ,6  ,5  ,'MICT, NITA,  MOFPED, OAG'),
(18 ,6  ,6  ,'Parliament, OP,  OPM, OAG,  MOFPED, NPA'),
(18 ,6  ,7  ,'OP, OPM,  MOFPED, MoPS,  NPA');
go

select * from ndp3.Interventions;