use Uganda;
go

drop table if exists NDP3.Acronyms;
go

create table NDP3.Acronyms
(
	AcronymID int identity,
	Acronym nvarchar(10),
	Description nvarchar(100),
	constraint PK_Acronyms primary key (AcronymID)
);

insert NDP3.Acronyms (Acronym, Description) values
('ACD','Anti-Corruption Division'),
('AfCFTA','African Continental Free Trade Area'),
('AfDB','African Development Bank'),
('AFROSAL','African Organization of Supreme Audit Institutions'),
('AGI','Agro-Industrialization'),
('ASSIP','Accountability Sector Strategic Investment Plan'),
('BCCU','Bugisu Coffee Cooperative Union'),
('BTVET','Business, Technical and Vocational Training'),
('BOU','Bank of Uganda'),
('CDOs','Community Development Officers'),
('CMA','Capital Markets Authority'),
('CME','Community Mobilization and Empowerment'),
('CNDPF','Comprehensive National Development Planning Framework'),
('COMESA','Common Market for East and Southern Africa'),
('CNOOC','China National Offshore Oil Corporation'),
('CSOs','Civil Society Organisations'),
('CTC','Cut, Tear and Curl'),
('DDA','Dairy Development Authority'),
('DDEG','Discretionary Development Equalisation Grant'),
('DEI','Directorate of Ethics and Integrity'),
('DFS','Digital Financial Services'),
('DIT','Directorate f Industrial Training'),
('DLG','District Local Government'),
('DPP','Directorate of Public Prosecution'),
('DPs','Development Partners'),
('DRMS','Domestic Revenue Mobilisation Strategy'),
('EAC','East African Community'),
('EBA','Everything But Arms'),
('ECCE','Early Childhood Care and Education'),
('ECD','Early Childhood Development'),
('EIA','Environmental Impact Assessment'),
('EITI','Extractive Industries Transparency Initiative'),
('EPRC','Economic Policy Research Centre'),
('ERA','Electricity Regulatory Authority'),
('FBOs','Faith Based Organizations'),
('FDC','Forum for Democratic Change'),
('FDI','Foreign Direct Investment'),
('FID','Final Investment Decision'),
('FGM','Female Genital Mutilation'),
('FSDS','Financial Sector Development Services'),
('GAPR','Government Annual Performance Report'),
('GCIC','Government Citizen Interaction Centre'),
('GDP','Gross Domestic Product'),
('GER','Gross Enrollment Ratio'),
('GKMA','Greater Kampala Metropolitan Area'),
('HCs','Health Centres'),
('HCI','Human Capital Index'),
('HDI','Human Development Index'),
('HESFEB','Higher Education Students Financing Board'),
('HIPC','Highly Indebted Poor Countries'),
('HRBA','Human Rights Based Approach'),
('HTTI','Hotel and Tourism Training Institute'),
('IBP','Integrated Bank of Projects'),
('ICBT','Informal Cross Border Trade'),
('ICT','Information and Communication Technology'),
('IFMIS','Integrated Finance Management Information System'),
('IG','Inspectorate of Government'),
('ITNS','Insecticides Treated Nets'),
('IPP','Integrated Personal and Payroll System'),
('IRA','Insurance Regulatory Authority'),
('ISO','International Standards Organization'),
('JLOS','Justice, Law and Order Sector'),
('KCCA','Kampala Capital City Authority'),
('KIBP','Kampala Industrial and Business Park'),
('KIIDP','Kampala Integrated Infrastructure Development Project'),
('LED','Local Economic Development'),
('LGs','Local Governments'),
('MoAAIF','Ministry of Agriculture Animal Industry and Fisheries'),
('MATIP','Market and Agricultural Trade Improvement Project'),
('MDAs','Ministries Departments and Agencies'),
('MoEMD','Ministry of Energy and Mineral Development'),
('MTEF','Medium Term Expenditure Framework'),
('MoTIC','Ministry of Trade Industry and Cooperatives'),
('MICE','Meetings, Incentives, Conferences and Events'),
('MIS','Management Information System'),
('MEACA','Ministry of East African Community Affairs'),
('MoDVA','Ministry of Defense and Veteran Affairs'),
('MoES','Ministry of Education and Sports'),
('MoFA','Ministry of Foreign Affairs'),
('MoFPED','Ministry of Finance Planning and Economic Development'),
('MoH','Ministry of Health'),
('MoGLSD','Ministry of Gender, Labour and Social Development'),
('MoIA','Ministry of Internal Affairs'),
('MoICTNG','Ministry of Information and Communication Technology and National Guidance'),
('MoJCA','Ministry of Justice and Constitutional Affairs'),
('MoLG','Ministry of Local Government'),
('MoLHUD','Ministry of Lands, Housing and Urban Development'),
('MoPS','Ministry of Public Service'),
('MoSTI','Ministry of Science Technology and Innovation'),
('MoTWA','Ministry of Tourism, Wildlife and Antiquities'),
('MoWE','Ministry of Water and Environment'),
('MoWT','Ministry of Works and Transport'),
('MPs','Members of Parliament'),
('MSMEs','Micro Small and Medium Enterprises'),
('MTR','Mid-Term Review'),
('NAADS','National Agricultural Advisory Services'),
('NAGRCDB','National Animal Genetic Resource Centre and Data Bank'),
('NARO','National Agricultural Research Organization'),
('NDCs','Nationally Determined Contributions'),
('NER','Net Enrollment Ratio'),
('NFA','National Forestry Authority'),
('NFLC','National Farmer Leadership Centre'),
('NRI','Networked Readiness Index'),
('NCHE','National Council of Higher Education'),
('NPA','National Planning Authority'),
('NARO','National Agricultural Research Organization'),
('NCDC','National Curriculum Development Centre'),
('NCDs','Non-Communicable Diseases'),
('NDP','National Development Plan'),
('NDPI','First National Development Plan'),
('NDPII','Second National Development Plan'),
('NDPIII','Third National Development Plan'),
('NEMA','National Environment Management Authority'),
('NFA','National Forestry Authority'),
('NGOs','Non-Governmental Organizations'),
('NIMES','National Integrated Monitoring and Evaluation Strategy'),
('NITA','National Information Technology Authority'),
('NMT','Non-Motorized Transport'),
('NRM','National Resistance Movement'),
('NSS','National Statistics System'),
('NSSF','National Social Security Fund'),
('NTMs','Non-Tariff Measures'),
('OAG','Office of the Auditor General'),
('OP','Office of the President'),
('OPM','Office of the Prime Minister'),
('OPMIS','Office of the Prime Minister Management Information System'),
('OVCs','Orphans and other Vulnerable Children'),
('OWC','Operation Wealth Creation'),
('PAP','Project Affected Persons'),
('PAU','Petroleum Authority of Uganda'),
('PBS','Programme Based Budgeting System'),
('PEFA','Public Expenditure and Financial Accountability'),
('PFM','Public Finance Management'),
('PFMA','Public Finance Management Act'),
('PIBID','Presidential Initiative for Banana Industrial Development'),
('PIP','Public Investment Plan'),
('PIMS','Public Investment Management Strategy'),
('PPDA','Public Procurement and Disposal of Public Assets'),
('PPP','Public Private Partnership'),
('PRDP','Peace Reconstruction and Development Programme'),
('PSFU','Private Sector Foundation Uganda'),
('PSRs','Public Sector Reforms'),
('PWDs','Persons with Disabilities'),
('QHSSE','Quality Health Safety Security and Environment'),
('QMS','Quality Management Systems'),
('REA','Rural Electrification Agency'),
('REE','Rare Earth Elements'),
('RD','Research and Development'),
('ROM','Results Oriented Management'),
('ROW','Right of Way'),
('SACCOs','Saving ad Credit Cooperative Organizations'),
('SAGE','Social Assistance Grant for Empowerment'),
('SDGs','Sustainable Development Goals'),
('SDPs','Sector Development Plans'),
('SGR','Standard Gauge Railway'),
('STEM','Science, Technology, Engineering and Mathematics'),
('STI','Science Technology and Innovation'),
('STEI','Science Technology, Engineering and Innovation'),
('SMEs','Small and Medium Enterprises'),
('SOEs','State Owned Enterprises'),
('TRWR','Total Renewable Water Resources'),
('TSA','Tourism Satellite Account'),
('TSA','Treasury Single Account'),
('TVET','Technical and Vocational Education and Training'),
('UAC','Uganda AIDS Commission'),
('UBC','Uganda Broadcasting Cooperation'),
('UCAA','Uganda Civil Aviation Authority'),
('UBOS','Uganda Bureau of Statistics'),
('UCC','Uganda Communications Commission'),
('UCDA','Uganda Coffee Development Authority'),
('UCE','Uganda Commodity Exchange'),
('UDB','Uganda Development Bank'),
('UDC','Uganda Development Cooperation'),
('UEDCL','Uganda Electricity Distribution Company Limited'),
('UEGCL','Uganda Electricity Generation Company Limited'),
('UETCL','Uganda Electricity Transport Company Limited'),
('UEPB','Uganda Export Promotions Board'),
('UFZA','Uganda Free Zones Area'),
('UHI','Uganda Heart Institute'),
('UHRC','Uganda Human Rights Commission'),
('UICT','Uganda Institute of Information and Communications Technology'),
('UIRI','Uganda Industrial Research Institute'),
('ULC','Uganda Land Commission'),
('UMA','Uganda Manufactures Association'),
('UNBS','Uganda Bureau of Standards'),
('UNCST','Uganda National Council of Science and Technology'),
('UNDESA','United Nations Department of Economics and Social Affairs'),
('UNECA','United Nations Economic Commission for Africa'),
('UNHCC','Uganda National Housing and Construction Corporation'),
('UNMA','Uganda National Metrological Authority'),
('UNOC','Uganda National Oil Company'),
('UPC','Uganda People’s Congress'),
('UPE','Universal Primary Education'),
('UPF','Uganda Police Force'),
('UNHS','Uganda National Household Survey'),
('UNRA','Uganda Road Authority'),
('URA','Uganda Revenue Authority'),
('URBRA','Uganda Retirement Benefits Regulatory Authority'),
('URC','Uganda Railway Cooperation'),
('URF','Uganda Road Fund'),
('USE','Uganda Securities Exchange'),
('USSIA','Uganda Small Scale Industries Association'),
('USMID','Uganda Support to Municipal Infrastructure Development'),
('UTL','Uganda Telecom'),
('UIA','Uganda Investment Authority'),
('UIRI','Uganda Industrial Research Institute'),
('UMFSC','Uganda Microfinance Support Centre'),
('UNBS','Uganda National Bureau of Standards'),
('URA','Uganda Revenue Authority'),
('URSB','Uganda Registration Service Bureau'),
('UTB','Uganda Tourism Board'),
('UWA','Uganda Wildlife Authority'),
('UWEC','Uganda Wildlife Education Centre'),
('UWEP','Uganda Women Empowerment Programme'),
('UWRSA','Uganda Warehouse Receipt Systems Authority'),
('UWRTI','Uganda Wildlife Research and Training Institute'),
('UVRI','Uganda Virus Research Institute'),
('VHTs','Village Health Teams'),
('WASH','Water Sanitation and Hygiene'),
('WHO','World Health Organization'),
('WIPO','World Intellectual Property Organization'),
('YLP','Youth Livelihood Programme'),
('ZARDIs','Zonal Agricultural Research and Development Institutes');