use Uganda;
go

create table ndp3.Acronyms
(
	AcronymID int,
	Name nvarchar(10),
	Description nvarchar(80),
	constraint PK_Acronyms primary key (AcronymID),
	constraint UQ_Acronyms_Name unique (Name),
	constraint UQ_Acronyms_Description unique (Description)
);

-- ------------------------------------------------------------------------------------------------------------
-- Stage 1: Require structurally clean data.
-- ------------------------------------------------------------------------------------------------------------

--declare @T1 table
--(
--	Name nvarchar(10), 
--	Description nvarchar(80),
--	primary key (Name),
--	unique(Description)
--);

--insert @T1 (Name, Description) values
--('ACD','Anti-Corruption Division'),
--('AfCFTA','African Continental Free Trade Area'),
--('AfDB','African Development Bank'),
--('AFROSAL','African Organization of Supreme Audit Institutions'),
--('AGI','Agro-Industrialization'),
--('ASSIP','Accountability Sector Strategic Investment Plan'),
--('BCCU','Bugisu Coffee Cooperative Union'),
--('BTVET','Business, Technical and Vocational Training'),
--('BOU','Bank of Uganda'),
--('CDOs','Community Development Officers'),
--('CMA','Capital Markets Authority'),
--('CME','Community Mobilization and Empowerment'),
--('CNDPF','Comprehensive National Development Planning Framework'),
--('COMESA','Common Market for East and Southern Africa'),
--('CNOOC','China National Offshore Oil Corporation'),
--('CSOs','Civil Society Organisations'),
--('CTC','Cut, Tear and Curl'),
--('DDA','Dairy Development Authority'),
--('DDEG','Discretionary Development Equalisation Grant'),
--('DEI','Directorate of Ethics and Integrity'),
--('DFS','Digital Financial Services'),
--('DIT','Directorate f Industrial Training'),
--('DLG','District Local Government'),
--('DPP','Directorate of Public Prosecution'),
--('DPs','Development Partners'),
--('DRMS','Domestic Revenue Mobilisation Strategy'),
--('EAC','East African Community'),
--('EBA','Everything But Arms'),
--('ECCE','Early Childhood Care and Education'),
--('ECD','Early Childhood Development'),
--('EIA','Environmental Impact Assessment'),
--('EITI','Extractive Industries Transparency Initiative'),
--('EPRC','Economic Policy Research Centre'),
--('ERA','Electricity Regulatory Authority'),
--('FBOs','Faith Based Organizations'),
--('FDC','Forum for Democratic Change'),
--('FDI','Foreign Direct Investment'),
--('FID','Final Investment Decision'),
--('FGM','Female Genital Mutilation'),
--('FSDS','Financial Sector Development Services'),
--('GAPR','Government Annual Performance Report'),
--('GCIC','Government Citizen Interaction Centre'),
--('GDP','Gross Domestic Product'),
--('GER','Gross Enrollment Ratio'),
--('GKMA','Greater Kampala Metropolitan Area'),
--('HCs','Health Centres'),
--('HCI','Human Capital Index'),
--('HDI','Human Development Index'),
--('HESFEB','Higher Education Students Financing Board'),
--('HIPC','Highly Indebted Poor Countries'),
--('HRBA','Human Rights Based Approach'),
--('HTTI','Hotel and Tourism Training Institute'),
--('IBP','Integrated Bank of Projects'),
--('ICBT','Informal Cross Border Trade'),
--('ICT','Information and Communication Technology'),
--('IFMIS','Integrated Finance Management Information System'),
--('IG','Inspectorate of Government'),
--('ITNS','Insecticides Treated Nets'),
--('IPP','Integrated Personal and Payroll System'),
--('IRA','Insurance Regulatory Authority'),
--('ISO','International Standards Organization'),
--('JLOS','Justice, Law and Order Sector'),
--('KCCA','Kampala Capital City Authority'),
--('KIBP','Kampala Industrial and Business Park'),
--('KIIDP','Kampala Integrated Infrastructure Development Project'),
--('LED','Local Economic Development'),
--('LGs','Local Governments'),
--('MoAAIF','Ministry of Agriculture Animal Industry and Fisheries'),
--('MATIP','Market and Agricultural Trade Improvement Project'),
--('MDAs','Ministries Departments and Agencies'),
--('MoEMD','Ministry of Energy and Mineral Development'),
--('MTEF','Medium Term Expenditure Framework'),
--('MoTIC','Ministry of Trade Industry and Cooperatives'),
--('MICE','Meetings, Incentives, Conferences and Events'),
--('MIS','Management Information System'),
--('MEACA','Ministry of East African Community Affairs'),
--('MoDVA','Ministry of Defense and Veteran Affairs'),
--('MoES','Ministry of Education and Sports'),
--('MoFA','Ministry of Foreign Affairs'),
--('MoFPED','Ministry of Finance Planning and Economic Development'),
--('MoH','Ministry of Health'),
--('MoGLSD','Ministry of Gender, Labour and Social Development'),
--('MoIA','Ministry of Internal Affairs'),
--('MoICTNG','Ministry of Information and Communication Technology and National Guidance'),
--('MoJCA','Ministry of Justice and Constitutional Affairs'),
--('MoLG','Ministry of Local Government'),
--('MoLHUD','Ministry of Lands, Housing and Urban Development'),
--('MoPS','Ministry of Public Service'),
--('MoSTI','Ministry of Science Technology and Innovation'),
--('MoTWA','Ministry of Tourism, Wildlife and Antiquities'),
--('MoWE','Ministry of Water and Environment'),
--('MoWT','Ministry of Works and Transport'),
--('MPs','Members of Parliament'),
--('MSMEs','Micro Small and Medium Enterprises'),
--('MTR','Mid-Term Review'),
--('NAADS','National Agricultural Advisory Services'),
--('NAGRCDB','National Animal Genetic Resource Centre and Data Bank'),
--('NDCs','Nationally Determined Contributions'),
--('NER','Net Enrollment Ratio'),
--('NFLC','National Farmer Leadership Centre'),
--('NRI','Networked Readiness Index'),
--('NCHE','National Council of Higher Education'),
--('NPA','National Planning Authority'),
--('NARO','National Agricultural Research Organization'),
--('NCDC','National Curriculum Development Centre'),
--('NCDs','Non-Communicable Diseases'),
--('NDP','National Development Plan'),
--('NDPI','First National Development Plan'),
--('NDPII','Second National Development Plan'),
--('NDPIII','Third National Development Plan'),
--('NEMA','National Environment Management Authority'),
--('NFA','National Forestry Authority'),
--('NGOs','Non-Governmental Organizations'),
--('NIMES','National Integrated Monitoring and Evaluation Strategy'),
--('NITA','National Information Technology Authority'),
--('NMT','Non-Motorized Transport'),
--('NRM','National Resistance Movement'),
--('NSS','National Statistics System'),
--('NSSF','National Social Security Fund'),
--('NTMs','Non-Tariff Measures'),
--('OAG','Office of the Auditor General'),
--('OP','Office of the President'),
--('OPM','Office of the Prime Minister'),
--('OPMIS','Office of the Prime Minister Management Information System'),
--('OVCs','Orphans and other Vulnerable Children'),
--('OWC','Operation Wealth Creation'),
--('PAP','Project Affected Persons'),
--('PAU','Petroleum Authority of Uganda'),
--('PBS','Programme Based Budgeting System'),
--('PEFA','Public Expenditure and Financial Accountability'),
--('PFM','Public Finance Management'),
--('PFMA','Public Finance Management Act'),
--('PIBID','Presidential Initiative for Banana Industrial Development'),
--('PIP','Public Investment Plan'),
--('PIMS','Public Investment Management Strategy'),
--('PPDA','Public Procurement and Disposal of Public Assets'),
--('PPP','Public Private Partnership'),
--('PRDP','Peace Reconstruction and Development Programme'),
--('PSFU','Private Sector Foundation Uganda'),
--('PSRs','Public Sector Reforms'),
--('PWDs','Persons with Disabilities'),
--('QHSSE','Quality Health Safety Security and Environment'),
--('QMS','Quality Management Systems'),
--('REA','Rural Electrification Agency'),
--('REE','Rare Earth Elements'),
--('RD','Research and Development'),
--('ROM','Results Oriented Management'),
--('ROW','Right of Way'),
--('SACCOs','Saving ad Credit Cooperative Organizations'),
--('SAGE','Social Assistance Grant for Empowerment'),
--('SDGs','Sustainable Development Goals'),
--('SDPs','Sector Development Plans'),
--('SGR','Standard Gauge Railway'),
--('STEM','Science, Technology, Engineering and Mathematics'),
--('STI','Science Technology and Innovation'),
--('STEI','Science Technology, Engineering and Innovation'),
--('SMEs','Small and Medium Enterprises'),
--('SOEs','State Owned Enterprises'),
--('TRWR','Total Renewable Water Resources'),
--('TOSA','Tourism Satellite Account'),
--('TRSA','Treasury Single Account'),
--('TVET','Technical and Vocational Education and Training'),
--('UAC','Uganda AIDS Commission'),
--('UBC','Uganda Broadcasting Cooperation'),
--('UCAA','Uganda Civil Aviation Authority'),
--('UBOS','Uganda Bureau of Statistics'),
--('UCC','Uganda Communications Commission'),
--('UCDA','Uganda Coffee Development Authority'),
--('UCE','Uganda Commodity Exchange'),
--('UDB','Uganda Development Bank'),
--('UDC','Uganda Development Cooperation'),
--('UEDCL','Uganda Electricity Distribution Company Limited'),
--('UEGCL','Uganda Electricity Generation Company Limited'),
--('UETCL','Uganda Electricity Transport Company Limited'),
--('UEPB','Uganda Export Promotions Board'),
--('UFZA','Uganda Free Zones Area'),
--('UHI','Uganda Heart Institute'),
--('UHRC','Uganda Human Rights Commission'),
--('UICT','Uganda Institute of Information and Communications Technology'),
--('ULC','Uganda Land Commission'),
--('UMA','Uganda Manufactures Association'),
--('UNCST','Uganda National Council of Science and Technology'),
--('UNDESA','United Nations Department of Economics and Social Affairs'),
--('UNECA','United Nations Economic Commission for Africa'),
--('UNHCC','Uganda National Housing and Construction Corporation'),
--('UNMA','Uganda National Metrological Authority'),
--('UNOC','Uganda National Oil Company'),
--('UPC','Uganda People’s Congress'),
--('UPE','Universal Primary Education'),
--('UPF','Uganda Police Force'),
--('UNHS','Uganda National Household Survey'),
--('UNRA','Uganda Road Authority'),
--('URBRA','Uganda Retirement Benefits Regulatory Authority'),
--('URC','Uganda Railway Cooperation'),
--('URF','Uganda Road Fund'),
--('USE','Uganda Securities Exchange'),
--('USSIA','Uganda Small Scale Industries Association'),
--('USMID','Uganda Support to Municipal Infrastructure Development'),
--('UTL','Uganda Telecom'),
--('UIA','Uganda Investment Authority'),
--('UIRI','Uganda Industrial Research Institute'),
--('UMFSC','Uganda Microfinance Support Centre'),
--('UNBS','Uganda National Bureau of Standards'),
--('URA','Uganda Revenue Authority'),
--('URSB','Uganda Registration Service Bureau'),
--('UTB','Uganda Tourism Board'),
--('UWA','Uganda Wildlife Authority'),
--('UWEC','Uganda Wildlife Education Centre'),
--('UWEP','Uganda Women Empowerment Programme'),
--('UWRSA','Uganda Warehouse Receipt Systems Authority'),
--('UWRTI','Uganda Wildlife Research and Training Institute'),
--('UVRI','Uganda Virus Research Institute'),
--('VHTs','Village Health Teams'),
--('WASH','Water Sanitation and Hygiene'),
--('WHO','World Health Organization'),
--('WIPO','World Intellectual Property Organization'),
--('YLP','Youth Livelihood Programme'),
--('ZARDIs','Zonal Agricultural Research and Development Institutes');

-- ------------------------------------------------------------------------------------------------------------
-- Stage 2: Add a primary key.
-- ------------------------------------------------------------------------------------------------------------

--declare @T2 table 
--(
--	AcronymID int identity,
--	Name nvarchar(10), 
--	Description nvarchar(80),
--	primary key (AcronymID),
--	unique(Name),
--	unique(Description)
--);

--insert @T2 
--select 
--	* 
--from 
--	@T1 
--order by 
--	Name;

-- ------------------------------------------------------------------------------------------------------------
-- Stage 3: Create a persistable script.
-- ------------------------------------------------------------------------------------------------------------

--select
--	'('+
--	convert(nchar(4),AcronymID)+','+
--	char(39)+convert(nchar(11),Name+char(39))+','+
--	char(39)+convert(nchar(81),Description+char(39))+
--	'),'
--from 
--	@T2
--order by
--	AcronymID;

-- ------------------------------------------------------------------------------------------------------------
-- Stage 4: Insert the data.
-- ------------------------------------------------------------------------------------------------------------

insert ndp3.Acronyms (AcronymID, Name, Description) values
(1   ,'ACD'       ,'Anti-Corruption Division'                                                        ),
(2   ,'AfCFTA'    ,'African Continental Free Trade Area'                                             ),
(3   ,'AfDB'      ,'African Development Bank'                                                        ),
(4   ,'AFROSAL'   ,'African Organization of Supreme Audit Institutions'                              ),
(5   ,'AGI'       ,'Agro-Industrialization'                                                          ),
(6   ,'ASSIP'     ,'Accountability Sector Strategic Investment Plan'                                 ),
(7   ,'BCCU'      ,'Bugisu Coffee Cooperative Union'                                                 ),
(8   ,'BOU'       ,'Bank of Uganda'                                                                  ),
(9   ,'BTVET'     ,'Business, Technical and Vocational Training'                                     ),
(10  ,'CDOs'      ,'Community Development Officers'                                                  ),
(11  ,'CMA'       ,'Capital Markets Authority'                                                       ),
(12  ,'CME'       ,'Community Mobilization and Empowerment'                                          ),
(13  ,'CNDPF'     ,'Comprehensive National Development Planning Framework'                           ),
(14  ,'CNOOC'     ,'China National Offshore Oil Corporation'                                         ),
(15  ,'COMESA'    ,'Common Market for East and Southern Africa'                                      ),
(16  ,'CSOs'      ,'Civil Society Organisations'                                                     ),
(17  ,'CTC'       ,'Cut, Tear and Curl'                                                              ),
(18  ,'DDA'       ,'Dairy Development Authority'                                                     ),
(19  ,'DDEG'      ,'Discretionary Development Equalisation Grant'                                    ),
(20  ,'DEI'       ,'Directorate of Ethics and Integrity'                                             ),
(21  ,'DFS'       ,'Digital Financial Services'                                                      ),
(22  ,'DIT'       ,'Directorate f Industrial Training'                                               ),
(23  ,'DLG'       ,'District Local Government'                                                       ),
(24  ,'DPP'       ,'Directorate of Public Prosecution'                                               ),
(25  ,'DPs'       ,'Development Partners'                                                            ),
(26  ,'DRMS'      ,'Domestic Revenue Mobilisation Strategy'                                          ),
(27  ,'EAC'       ,'East African Community'                                                          ),
(28  ,'EBA'       ,'Everything But Arms'                                                             ),
(29  ,'ECCE'      ,'Early Childhood Care and Education'                                              ),
(30  ,'ECD'       ,'Early Childhood Development'                                                     ),
(31  ,'EIA'       ,'Environmental Impact Assessment'                                                 ),
(32  ,'EITI'      ,'Extractive Industries Transparency Initiative'                                   ),
(33  ,'EPRC'      ,'Economic Policy Research Centre'                                                 ),
(34  ,'ERA'       ,'Electricity Regulatory Authority'                                                ),
(35  ,'FBOs'      ,'Faith Based Organizations'                                                       ),
(36  ,'FDC'       ,'Forum for Democratic Change'                                                     ),
(37  ,'FDI'       ,'Foreign Direct Investment'                                                       ),
(38  ,'FGM'       ,'Female Genital Mutilation'                                                       ),
(39  ,'FID'       ,'Final Investment Decision'                                                       ),
(40  ,'FSDS'      ,'Financial Sector Development Services'                                           ),
(41  ,'GAPR'      ,'Government Annual Performance Report'                                            ),
(42  ,'GCIC'      ,'Government Citizen Interaction Centre'                                           ),
(43  ,'GDP'       ,'Gross Domestic Product'                                                          ),
(44  ,'GER'       ,'Gross Enrollment Ratio'                                                          ),
(45  ,'GKMA'      ,'Greater Kampala Metropolitan Area'                                               ),
(46  ,'HCI'       ,'Human Capital Index'                                                             ),
(47  ,'HCs'       ,'Health Centres'                                                                  ),
(48  ,'HDI'       ,'Human Development Index'                                                         ),
(49  ,'HESFEB'    ,'Higher Education Students Financing Board'                                       ),
(50  ,'HIPC'      ,'Highly Indebted Poor Countries'                                                  ),
(51  ,'HRBA'      ,'Human Rights Based Approach'                                                     ),
(52  ,'HTTI'      ,'Hotel and Tourism Training Institute'                                            ),
(53  ,'IBP'       ,'Integrated Bank of Projects'                                                     ),
(54  ,'ICBT'      ,'Informal Cross Border Trade'                                                     ),
(55  ,'ICT'       ,'Information and Communication Technology'                                        ),
(56  ,'IFMIS'     ,'Integrated Finance Management Information System'                                ),
(57  ,'IG'        ,'Inspectorate of Government'                                                      ),
(58  ,'IPP'       ,'Integrated Personal and Payroll System'                                          ),
(59  ,'IRA'       ,'Insurance Regulatory Authority'                                                  ),
(60  ,'ISO'       ,'International Standards Organization'                                            ),
(61  ,'ITNS'      ,'Insecticides Treated Nets'                                                       ),
(62  ,'JLOS'      ,'Justice, Law and Order Sector'                                                   ),
(63  ,'KCCA'      ,'Kampala Capital City Authority'                                                  ),
(64  ,'KIBP'      ,'Kampala Industrial and Business Park'                                            ),
(65  ,'KIIDP'     ,'Kampala Integrated Infrastructure Development Project'                           ),
(66  ,'LED'       ,'Local Economic Development'                                                      ),
(67  ,'LGs'       ,'Local Governments'                                                               ),
(68  ,'MATIP'     ,'Market and Agricultural Trade Improvement Project'                               ),
(69  ,'MDAs'      ,'Ministries Departments and Agencies'                                             ),
(70  ,'MEACA'     ,'Ministry of East African Community Affairs'                                      ),
(71  ,'MICE'      ,'Meetings, Incentives, Conferences and Events'                                    ),
(72  ,'MIS'       ,'Management Information System'                                                   ),
(73  ,'MoAAIF'    ,'Ministry of Agriculture Animal Industry and Fisheries'                           ),
(74  ,'MoDVA'     ,'Ministry of Defense and Veteran Affairs'                                         ),
(75  ,'MoEMD'     ,'Ministry of Energy and Mineral Development'                                      ),
(76  ,'MoES'      ,'Ministry of Education and Sports'                                                ),
(77  ,'MoFA'      ,'Ministry of Foreign Affairs'                                                     ),
(78  ,'MoFPED'    ,'Ministry of Finance Planning and Economic Development'                           ),
(79  ,'MoGLSD'    ,'Ministry of Gender, Labour and Social Development'                               ),
(80  ,'MoH'       ,'Ministry of Health'                                                              ),
(81  ,'MoIA'      ,'Ministry of Internal Affairs'                                                    ),
(82  ,'MoICTNG'   ,'Ministry of Information and Communication Technology and National Guidance'      ),
(83  ,'MoJCA'     ,'Ministry of Justice and Constitutional Affairs'                                  ),
(84  ,'MoLG'      ,'Ministry of Local Government'                                                    ),
(85  ,'MoLHUD'    ,'Ministry of Lands, Housing and Urban Development'                                ),
(86  ,'MoPS'      ,'Ministry of Public Service'                                                      ),
(87  ,'MoSTI'     ,'Ministry of Science Technology and Innovation'                                   ),
(88  ,'MoTIC'     ,'Ministry of Trade Industry and Cooperatives'                                     ),
(89  ,'MoTWA'     ,'Ministry of Tourism, Wildlife and Antiquities'                                   ),
(90  ,'MoWE'      ,'Ministry of Water and Environment'                                               ),
(91  ,'MoWT'      ,'Ministry of Works and Transport'                                                 ),
(92  ,'MPs'       ,'Members of Parliament'                                                           ),
(93  ,'MSMEs'     ,'Micro Small and Medium Enterprises'                                              ),
(94  ,'MTEF'      ,'Medium Term Expenditure Framework'                                               ),
(95  ,'MTR'       ,'Mid-Term Review'                                                                 ),
(96  ,'NAADS'     ,'National Agricultural Advisory Services'                                         ),
(97  ,'NAGRCDB'   ,'National Animal Genetic Resource Centre and Data Bank'                           ),
(98  ,'NARO'      ,'National Agricultural Research Organization'                                     ),
(99  ,'NCDC'      ,'National Curriculum Development Centre'                                          ),
(100 ,'NCDs'      ,'Non-Communicable Diseases'                                                       ),
(101 ,'NCHE'      ,'National Council of Higher Education'                                            ),
(102 ,'NDCs'      ,'Nationally Determined Contributions'                                             ),
(103 ,'NDP'       ,'National Development Plan'                                                       ),
(104 ,'NDPI'      ,'First National Development Plan'                                                 ),
(105 ,'NDPII'     ,'Second National Development Plan'                                                ),
(106 ,'NDPIII'    ,'Third National Development Plan'                                                 ),
(107 ,'NEMA'      ,'National Environment Management Authority'                                       ),
(108 ,'NER'       ,'Net Enrollment Ratio'                                                            ),
(109 ,'NFA'       ,'National Forestry Authority'                                                     ),
(110 ,'NFLC'      ,'National Farmer Leadership Centre'                                               ),
(111 ,'NGOs'      ,'Non-Governmental Organizations'                                                  ),
(112 ,'NIMES'     ,'National Integrated Monitoring and Evaluation Strategy'                          ),
(113 ,'NITA'      ,'National Information Technology Authority'                                       ),
(114 ,'NMT'       ,'Non-Motorized Transport'                                                         ),
(115 ,'NPA'       ,'National Planning Authority'                                                     ),
(116 ,'NRI'       ,'Networked Readiness Index'                                                       ),
(117 ,'NRM'       ,'National Resistance Movement'                                                    ),
(118 ,'NSS'       ,'National Statistics System'                                                      ),
(119 ,'NSSF'      ,'National Social Security Fund'                                                   ),
(120 ,'NTMs'      ,'Non-Tariff Measures'                                                             ),
(121 ,'OAG'       ,'Office of the Auditor General'                                                   ),
(122 ,'OP'        ,'Office of the President'                                                         ),
(123 ,'OPM'       ,'Office of the Prime Minister'                                                    ),
(124 ,'OPMIS'     ,'Office of the Prime Minister Management Information System'                      ),
(125 ,'OVCs'      ,'Orphans and other Vulnerable Children'                                           ),
(126 ,'OWC'       ,'Operation Wealth Creation'                                                       ),
(127 ,'PAP'       ,'Project Affected Persons'                                                        ),
(128 ,'PAU'       ,'Petroleum Authority of Uganda'                                                   ),
(129 ,'PBS'       ,'Programme Based Budgeting System'                                                ),
(130 ,'PEFA'      ,'Public Expenditure and Financial Accountability'                                 ),
(131 ,'PFM'       ,'Public Finance Management'                                                       ),
(132 ,'PFMA'      ,'Public Finance Management Act'                                                   ),
(133 ,'PIBID'     ,'Presidential Initiative for Banana Industrial Development'                       ),
(134 ,'PIMS'      ,'Public Investment Management Strategy'                                           ),
(135 ,'PIP'       ,'Public Investment Plan'                                                          ),
(136 ,'PPDA'      ,'Public Procurement and Disposal of Public Assets'                                ),
(137 ,'PPP'       ,'Public Private Partnership'                                                      ),
(138 ,'PRDP'      ,'Peace Reconstruction and Development Programme'                                  ),
(139 ,'PSFU'      ,'Private Sector Foundation Uganda'                                                ),
(140 ,'PSRs'      ,'Public Sector Reforms'                                                           ),
(141 ,'PWDs'      ,'Persons with Disabilities'                                                       ),
(142 ,'QHSSE'     ,'Quality Health Safety Security and Environment'                                  ),
(143 ,'QMS'       ,'Quality Management Systems'                                                      ),
(144 ,'RD'        ,'Research and Development'                                                        ),
(145 ,'REA'       ,'Rural Electrification Agency'                                                    ),
(146 ,'REE'       ,'Rare Earth Elements'                                                             ),
(147 ,'ROM'       ,'Results Oriented Management'                                                     ),
(148 ,'ROW'       ,'Right of Way'                                                                    ),
(149 ,'SACCOs'    ,'Saving ad Credit Cooperative Organizations'                                      ),
(150 ,'SAGE'      ,'Social Assistance Grant for Empowerment'                                         ),
(151 ,'SDGs'      ,'Sustainable Development Goals'                                                   ),
(152 ,'SDPs'      ,'Sector Development Plans'                                                        ),
(153 ,'SGR'       ,'Standard Gauge Railway'                                                          ),
(154 ,'SMEs'      ,'Small and Medium Enterprises'                                                    ),
(155 ,'SOEs'      ,'State Owned Enterprises'                                                         ),
(156 ,'STEI'      ,'Science Technology, Engineering and Innovation'                                  ),
(157 ,'STEM'      ,'Science, Technology, Engineering and Mathematics'                                ),
(158 ,'STI'       ,'Science Technology and Innovation'                                               ),
(159 ,'TOSA'      ,'Tourism Satellite Account'                                                       ),
(160 ,'TRSA'      ,'Treasury Single Account'                                                         ),
(161 ,'TRWR'      ,'Total Renewable Water Resources'                                                 ),
(162 ,'TVET'      ,'Technical and Vocational Education and Training'                                 ),
(163 ,'UAC'       ,'Uganda AIDS Commission'                                                          ),
(164 ,'UBC'       ,'Uganda Broadcasting Cooperation'                                                 ),
(165 ,'UBOS'      ,'Uganda Bureau of Statistics'                                                     ),
(166 ,'UCAA'      ,'Uganda Civil Aviation Authority'                                                 ),
(167 ,'UCC'       ,'Uganda Communications Commission'                                                ),
(168 ,'UCDA'      ,'Uganda Coffee Development Authority'                                             ),
(169 ,'UCE'       ,'Uganda Commodity Exchange'                                                       ),
(170 ,'UDB'       ,'Uganda Development Bank'                                                         ),
(171 ,'UDC'       ,'Uganda Development Cooperation'                                                  ),
(172 ,'UEDCL'     ,'Uganda Electricity Distribution Company Limited'                                 ),
(173 ,'UEGCL'     ,'Uganda Electricity Generation Company Limited'                                   ),
(174 ,'UEPB'      ,'Uganda Export Promotions Board'                                                  ),
(175 ,'UETCL'     ,'Uganda Electricity Transport Company Limited'                                    ),
(176 ,'UFZA'      ,'Uganda Free Zones Area'                                                          ),
(177 ,'UHI'       ,'Uganda Heart Institute'                                                          ),
(178 ,'UHRC'      ,'Uganda Human Rights Commission'                                                  ),
(179 ,'UIA'       ,'Uganda Investment Authority'                                                     ),
(180 ,'UICT'      ,'Uganda Institute of Information and Communications Technology'                   ),
(181 ,'UIRI'      ,'Uganda Industrial Research Institute'                                            ),
(182 ,'ULC'       ,'Uganda Land Commission'                                                          ),
(183 ,'UMA'       ,'Uganda Manufactures Association'                                                 ),
(184 ,'UMFSC'     ,'Uganda Microfinance Support Centre'                                              ),
(185 ,'UNBS'      ,'Uganda National Bureau of Standards'                                             ),
(186 ,'UNCST'     ,'Uganda National Council of Science and Technology'                               ),
(187 ,'UNDESA'    ,'United Nations Department of Economics and Social Affairs'                       ),
(188 ,'UNECA'     ,'United Nations Economic Commission for Africa'                                   ),
(189 ,'UNHCC'     ,'Uganda National Housing and Construction Corporation'                            ),
(190 ,'UNHS'      ,'Uganda National Household Survey'                                                ),
(191 ,'UNMA'      ,'Uganda National Metrological Authority'                                          ),
(192 ,'UNOC'      ,'Uganda National Oil Company'                                                     ),
(193 ,'UNRA'      ,'Uganda Road Authority'                                                           ),
(194 ,'UPC'       ,'Uganda People’s Congress'                                                        ),
(195 ,'UPE'       ,'Universal Primary Education'                                                     ),
(196 ,'UPF'       ,'Uganda Police Force'                                                             ),
(197 ,'URA'       ,'Uganda Revenue Authority'                                                        ),
(198 ,'URBRA'     ,'Uganda Retirement Benefits Regulatory Authority'                                 ),
(199 ,'URC'       ,'Uganda Railway Cooperation'                                                      ),
(200 ,'URF'       ,'Uganda Road Fund'                                                                ),
(201 ,'URSB'      ,'Uganda Registration Service Bureau'                                              ),
(202 ,'USE'       ,'Uganda Securities Exchange'                                                      ),
(203 ,'USMID'     ,'Uganda Support to Municipal Infrastructure Development'                          ),
(204 ,'USSIA'     ,'Uganda Small Scale Industries Association'                                       ),
(205 ,'UTB'       ,'Uganda Tourism Board'                                                            ),
(206 ,'UTL'       ,'Uganda Telecom'                                                                  ),
(207 ,'UVRI'      ,'Uganda Virus Research Institute'                                                 ),
(208 ,'UWA'       ,'Uganda Wildlife Authority'                                                       ),
(209 ,'UWEC'      ,'Uganda Wildlife Education Centre'                                                ),
(210 ,'UWEP'      ,'Uganda Women Empowerment Programme'                                              ),
(211 ,'UWRSA'     ,'Uganda Warehouse Receipt Systems Authority'                                      ),
(212 ,'UWRTI'     ,'Uganda Wildlife Research and Training Institute'                                 ),
(213 ,'VHTs'      ,'Village Health Teams'                                                            ),
(214 ,'WASH'      ,'Water Sanitation and Hygiene'                                                    ),
(215 ,'WHO'       ,'World Health Organization'                                                       ),
(216 ,'WIPO'      ,'World Intellectual Property Organization'                                        ),
(217 ,'YLP'       ,'Youth Livelihood Programme'                                                      ),
(218 ,'ZARDIs'    ,'Zonal Agricultural Research and Development Institutes'                          );

-- ------------------------------------------------------------------------------------------------------------
-- Stage 5: Have a look.
-- ------------------------------------------------------------------------------------------------------------

--select * from ndp3.Acronyms;

select '1';
go