use Uganda;
go

create table I
(
	IndicatorID int,
	Name nvarchar(250),
	Reference nvarchar(10),
	ReferenceName as Reference + ' - ' + Name,
	Baseline decimal (14,4),
	Units nvarchar(50),
	constraint PK_I primary key (IndicatorID),
	constraint UQ_I_Name unique (Name),
	constraint UQ_I_Reference unique (Reference)
);

insert I (IndicatorID, Name, Reference, Baseline, Units) values
(1  ,'Increase Agricultural Real GDP growth rate                                                                                        ','01.01.01',3.8000        ,'Percent                         '),
(2  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Coffee                                           ','01.02.01',0.4920        ,'USD Billion                     '),
(3  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Tea                                              ','01.02.02',0.0910        ,'USD Billion                     '),
(4  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Fish                                             ','01.02.03',0.1460        ,'USD Billion                     '),
(5  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Dairy                                            ','01.02.04',0.0770        ,'USD Billion                     '),
(6  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Meat                                             ','01.02.05',0.0030        ,'USD Billion                     '),
(7  ,'Increase total Export value of priority agricultural commodities (USD Billion) - Maize                                            ','01.02.06',0.1250        ,'USD Billion                     '),
(8  ,'Increase the cumulative water for production storage capacity (Mcm)                                                               ','01.03.01',39.3000       ,'Mcm                             '),
(9  ,'Increase area under formal irrigation (ha)                                                                                        ','01.04.01',15147.0000    ,'ha                              '),
(10 ,'Increase the percentage of functional water for production facilities                                                             ','01.05.01',86.7000       ,'Percent                         '),
(11 ,'Increase the proportion of households that are food secure                                                                        ','01.06.01',69.0000       ,'Percent                         '),
(12 ,'Reduce the proportion of households dependent on subsistence agriculture as a main source of livelihood (percent)                 ','01.07.01',68.0000       ,'Percent                         '),
(13 ,'Number of jobs created in the agro-industrial value chain                                                                         ','01.08.01',0.0000        ,'Jobs                            '),
(14 ,'Labour productivity in agriculture (USD)                                                                                          ','01.09.01',2212.0000     ,'USD                             '),
(15 ,'Post-harvest losses for priority commodities (percent)                                                                            ','01.10.01',37.0000       ,'Percent                         '),
(16 ,'Storage capacity (MT)                                                                                                             ','01.11.01',550000.0000   ,'MT                              '),
(17 ,'Increase volume of copper produced (metric tonnes)                                                                                ','02.01.01',0.0000        ,'Metric Tonnes                   '),
(18 ,'Increase the value of refined Gold exports                                                                                        ','02.02.01',450.0000      ,'?                               '),
(19 ,'Increase the number of trained and skilled Geoscientists                                                                          ','02.03.01',108.0000      ,'Persons                         '),
(20 ,'Increase the value of investment into the exploration and processing of the selected minerals                                     ','02.04.01',0.8000        ,'?                               '),
(21 ,'Contribution of processed minerals to total manufactured exports (percent)                                                        ','02.05.01',5.0000        ,'Percent                         '),
(22 ,'Number of people employed mineral sector (million)                                                                                ','02.06.01',1.6000        ,'Million Persons                 '),
(23 ,'Increase the Volume of imported Iron and Steel (tonnes)                                                                           ','02.07.01',700000.0000   ,'Tonnes                          '),
(24 ,'Reduce the value of imported Iron and Steel (USD Mn)                                                                              ','02.08.01',370.0000      ,'USD Mn                          '),
(25 ,'Reduce the volume of imported inorganic fertilizers (tonnes)                                                                      ','02.09.01',75000.0000    ,'Tonnes                          '),
(26 ,'Reduce the Value of imported inorganic fertilizers (USD Mn)                                                                       ','02.10.01',26.0000       ,'USD Mn                          '),
(27 ,'Amount of revenue from oil and gas sector (UGX Bn)                                                                                ','03.01.01',62.9800       ,'UGX Bn                          '),
(28 ,'Increase the contribution of the Oil & Gas to GDP (percent)                                                                       ','03.02.01',3.0000        ,'Percent                         '),
(29 ,'Increase the proportion of investment in oil and gas to GDP (percent)                                                             ','03.03.01',20.0000       ,'Percent                         '),
(30 ,'Increase Ugandans employed in the oil and gas and gas related industries                                                          ','03.04.01',3400.0000     ,'Persons                         '),
(31 ,'Increase contracts awarded to local companies                                                                                     ','03.05.01',50.0000       ,'?                               '),
(32 ,'Investment in Oil and Gas (Bn)                                                                                                    ','03.06.01',0.0000        ,'Bn                              '),
(33 ,'Local Content (percent)                                                                                                           ','03.07.01',0.0000        ,'Percent                         '),
(34 ,'Increase the contribution of Tourism to GDP (percent)                                                                             ','04.01.01',7.3000        ,'Percent                         '),
(35 ,'Increase annual Foreign exchange earnings (USD - Bn)                                                                              ','04.02.01',1.4500        ,'USD - Bn                        '),
(36 ,'More Ugandans visiting key tourist attractions (Museums, National Parks, Source of the Nile and UWEC)                             ','04.03.01',646099.0000   ,'Persons                         '),
(37 ,'Increase average Inbound tourism revenues per leisure tourist (USD)                                                               ','04.04.01',1036.0000     ,'USD                             '),
(38 ,'Increase the number of International Tourist arrivals from the U.S., Europe, Middle East, Japan and China                         ','04.05.01',212616.0000   ,'Arrivals                        '),
(39 ,'Increase the number of direct flight routes to Europe and Asia                                                                    ','04.06.01',6.0000        ,'Flights                         '),
(40 ,'Increase tourism arrivals                                                                                                         ','04.07.01',1402409.0000  ,'Arrivals                        '),
(41 ,'Increase contribution of tourism to total employment, percent                                                                     ','04.08.01',6.3000        ,'Percent                         '),
(42 ,'Percentage of titled land                                                                                                         ','05.01.01',21.0000       ,'Percent                         '),
(43 ,'Increase water permit holders complying with permit conditions at the time of spot check - Ground water                           ','05.02.01',76.0000       ,'?                               '),
(44 ,'Increase water permit holders complying with permit conditions at the time of spot check - Surface water                          ','05.02.02',78.0000       ,'?                               '),
(45 ,'Increase water permit holders complying with permit conditions at the time of spot check - Waste water discharge permit conditions','05.02.03',63.0000       ,'?                               '),
(46 ,'Increase water samples complying with national standards - Water bodies                                                           ','05.03.01',0.0000        ,'?                               '),
(47 ,'Increase water samples complying with national standards - Supplies/water collection points                                       ','05.03.02',0.0000        ,'?                               '),
(48 ,'Increase land area covered by forests, percent                                                                                    ','05.04.01',9.1000        ,'Percent                         '),
(49 ,'Increase the proportion of land area covered by wetlands, percent                                                                 ','05.05.01',8.9000        ,'Percent                         '),
(50 ,'Increase permit holders complying with ESIA conditions at the time of spot check, percent                                         ','05.06.01',40.0000       ,'Percent                         '),
(51 ,'Increase accuracy of Meteorological Information, percent                                                                          ','05.07.01',60.0000       ,'Percent                         '),
(52 ,'Increase the percentage of automation of weather and climate network                                                              ','05.08.01',30.0000       ,'Percent                         '),
(53 ,'Average Annual Change in a Green House Gas (GHG) emissions (MtCO2e)                                                               ','05.09.01',1.3900        ,'MtCO2e                          '),
(54 ,'Reduce the number of deaths and missing persons and directly affected persons attributed to disasters per 100,000 population      ','05.10.01',150.0000      ,'Per 100,000                     '),
(55 ,'Increase the proportion of green jobs to total jobs                                                                               ','05.11.01',25.0000       ,'Percent                         '),
(56 ,'Reduce the informal sector                                                                                                        ','06.01.01',56.6000       ,'?                               '),
(57 ,'Increase in non-commercial lending to the private sector in key growth sectors                                                    ','06.02.01',1.5000        ,'?                               '),
(58 ,'Increase the proportion of public contracts and sub-contracts that are awarded to local firms                                     ','06.03.01',30.0000       ,'Percent                         '),
(59 ,'Increase the value of exports                                                                                                     ','06.04.01',5390.0000     ,'?                               '),
(60 ,'Increase the share of manufactured exports to total exports, percent                                                              ','07.01.01',12.3000       ,'Percent                         '),
(61 ,'Increase the industrial sector contribution to GDP (percent)                                                                      ','07.02.01',26.5000       ,'Percent                         '),
(62 ,'Increase contribution of manufacturing to industrial GDP                                                                          ','07.03.01',15.8000       ,'?                               '),
(63 ,'Increase the share of manufacturing jobs to total formal jobs (percent)                                                           ','07.04.01',9.0000        ,'Percent                         '),
(64 ,'Increase share of labour force employed in the industrial sector (percent)                                                        ','07.05.01',12.6000       ,'Percent                         '),
(65 ,'Increase manufacturing value added (percent of GDP)                                                                               ','07.06.01',8.3000        ,'Percent of GDP                  '),
(66 ,'Reduce average travel time - within GKM                                                                                           ','08.01.01',4.1400        ,'min/km                          '),
(67 ,'Reduce average travel time - within other cities                                                                                  ','08.01.02',0.0000        ,'min/km                          '),
(68 ,'Reduce average travel time - National Roads                                                                                       ','08.01.03',1.1300        ,'min/km                          '),
(69 ,'Reduce average travel time - District Roads                                                                                       ','08.01.04',1.0000        ,'min/km                          '),
(70 ,'Reduce average travel time - Inland water transport MW to PB                                                                      ','08.01.05',18.0000       ,'hrs                             '),
(71 ,'Reduce average travel time - Passenger rail services                                                                              ','08.01.06',0.7500        ,'min/km                          '),
(72 ,'Reduce average travel time - Freight rail services Mombasa to Kampala                                                             ','08.01.07',19.0000       ,'Days                            '),
(73 ,'Freight transportation costs - Inland (on Road): Murrum                                                                           ','08.02.01',1130.0000     ,'UGX                             '),
(74 ,'Freight transportation costs - Inland (on Road): Tarmac                                                                           ','08.02.02',802.0000      ,'?                               '),
(75 ,'Freight transportation costs - Inland (on Rail)                                                                                   ','08.02.03',0.0400        ,'USD                             '),
(76 ,'Freight transportation costs - Inland (on Water)                                                                                  ','08.02.04',500.0000      ,'UGX                             '),
(77 ,'Freight transportation costs - From coast to Kampala (on Road)                                                                    ','08.02.05',0.7700        ,'USD                             '),
(78 ,'Freight transportation costs - From coast to Kampala (on Rail)                                                                    ','08.02.06',0.0500        ,'USD                             '),
(79 ,'Freight transportation costs - From coast (MW) to Kampala (PB) (on Water)                                                         ','08.02.07',0.0600        ,'USD                             '),
(80 ,'Stock of transport infrastructure - Paved National Roads                                                                          ','08.03.01',4971.0000     ,'km                              '),
(81 ,'Stock of transport infrastructure - Paved urban roads                                                                             ','08.03.02',1253.0000     ,'km                              '),
(82 ,'Stock of transport infrastructure - Permanent way/railway road                                                                    ','08.03.03',262.0000      ,'km                              '),
(83 ,'Freight Cargo - Central Corridor - Export                                                                                         ','08.04.01',9168.0000     ,'?                               '),
(84 ,'Freight Cargo - Central Corridor - Import                                                                                         ','08.04.02',4142.0000     ,'?                               '),
(85 ,'Freight Cargo - Northern Corridor - Export                                                                                        ','08.05.01',10243.0000    ,'?                               '),
(86 ,'Freight Cargo - Northern Corridor - Import                                                                                        ','08.05.02',25360.0000    ,'?                               '),
(87 ,'Construction of Roll-on Roll-off vessels (international)                                                                          ','08.06.01',5.0000        ,'Vessels                         '),
(88 ,'Construction of domestic (Ro’Pax) passenger ferries                                                                               ','08.07.01',10.0000       ,'Ferries                         '),
(89 ,'Unit cost of building transport infrastructure - Upgrading roads to paved standard                                                ','08.08.01',3.1000        ,'Mn per km                       '),
(90 ,'Unit cost of building transport infrastructure - Rehabilitation/reconstruction of paved roads                                     ','08.08.02',1.8000        ,'Mn per km                       '),
(91 ,'Unit cost of building transport infrastructure - Average cost for construction of unpaved/ gravel road                            ','08.08.03',40.0000       ,'Mn per km                       '),
(92 ,'Unit cost of building transport infrastructure - Rehabilitation of metre gauge rail infrastructure                                ','08.08.04',5.0000        ,'Mn per km                       '),
(93 ,'Development of Aids to Navigation                                                                                                 ','08.09.01',0.0000        ,'?                               '),
(94 ,'Development of search and rescue facilities (USD)                                                                                 ','08.10.01',200000.0000   ,'USD                             '),
(95 ,'Average infrastructure life span - Tarmac roads                                                                                   ','08.11.01',18.0000       ,'Years                           '),
(96 ,'Average infrastructure life span - First class murram                                                                             ','08.11.02',2.0000        ,'Years                           '),
(97 ,'Fatality per 100,000 vehicles (road transport)                                                                                    ','08.12.01',26.0000       ,'Fatalities                      '),
(98 ,'Total fatalities (Water transport)                                                                                                ','08.13.01',160.0000      ,'Fatalities                      '),
(99 ,'Increase proportion of the population with access to electricity                                                                  ','09.01.01',24.0000       ,'Percent                         '),
(100,'Increase primary energy consumption (million tonnes of oil equivalent)                                                            ','09.02.01',15.2000       ,'Million tonnes of oil equivalent'),
(101,'Increase per capita electricity consumption (kwh per capita)                                                                      ','09.03.01',100.0000      ,'kwh per capita                  '),
(102,'Increase transmission capacity of High voltage transmission lines (km)                                                            ','09.04.01',2354.0000     ,'kw                              '),
(103,'Increase grid reliability (percent)                                                                                               ','09.05.01',0.0000        ,'Percent                         '),
(104,'Increase energy generation capacity (MW)                                                                                          ','09.06.01',984.0000      ,'MW                              '),
(105,'Increase the share of clean energy used for cooking                                                                               ','09.07.01',15.0000       ,'Percent                         '),
(106,'Reduce share of biomass Energy used for cooking (percent)                                                                         ','09.08.01',85.0000       ,'Percent                         '),
(107,'Increase ICT penetration - Internet penetration                                                                                   ','10.01.01',25.0000       ,'Percent                         '),
(108,'Increase ICT penetration - Digital Terrestrial TV signal coverage                                                                 ','10.01.02',56.0000       ,'Percent                         '),
(109,'Increase ICT penetration - Population covered by broadband services (percent)                                                     ','10.01.03',74.0000       ,'Percent                         '),
(110,'Reduce the cost of ICT devices and services - Unit cost of 1Mbps/month of internet                                                ','10.02.01',237.0000      ,'?                               '),
(111,'Reduce the cost of ICT devices and services - Unit cost of low entry smart phones (UGX)                                           ','10.02.02',100000.0000   ,'UGX                             '),
(112,'Reduce the cost of ICT devices and services - Cost of a computer (UGX)                                                            ','10.02.03',1600000.0000  ,'UGX                             '),
(113,'Increase fixed broad band connectivity                                                                                            ','10.03.01',167000.0000   ,'?                               '),
(114,'ICT contribution to GDP                                                                                                           ','10.04.01',2.0000        ,'?                               '),
(115,'ICT directly and indirectly created jobs                                                                                          ','10.05.01',0.0000        ,'Jobs                            '),
(116,'Proportion of government services online                                                                                          ','10.06.01',20.0000       ,'Percent                         '),
(117,'National broadband coverage with minimum speed of 8 Mbps                                                                          ','10.07.01',31.0000       ,'Percent                         '),
(118,'Decrease the average travel time per km in GKMA (min/km)                                                                          ','11.01.01',4.1400        ,'min/km                          '),
(119,'Increase the proportion of titled land, percent                                                                                   ','11.02.01',21.0000       ,'Percent                         '),
(120,'Increase paved urban roads                                                                                                        ','11.03.01',1253.6900     ,'?                               '),
(121,'Increase proportion of paved urban roads to total urban roads, percent                                                            ','11.04.01',6.1000        ,'Percent                         '),
(122,'Decrease urban unemployment rate (percent)                                                                                        ','11.05.01',14.4100       ,'Percent                         '),
(123,'Proportion of urban population living in slums and informal settlements                                                           ','11.06.01',60.0000       ,'Percent                         '),
(124,'Reduce the acute Housing deficit (Million)                                                                                        ','11.07.01',2.2000        ,'?                               '),
(125,'Improve the efficiency of solid waste collection                                                                                  ','11.08.01',30.0000       ,'?                               '),
(126,'Increase Quality adjusted years of schooling                                                                                      ','12.01.01',4.5000        ,'Years                           '),
(127,'Increase average years of schooling                                                                                               ','12.02.01',6.1000        ,'Years                           '),
(128,'Reduced prevalence of under 5 Stunting, percent                                                                                   ','12.03.01',28.9000       ,'Percent                         '),
(129,'Improve unionization density, percent                                                                                             ','12.04.01',6.0000        ,'Percent                         '),
(130,'Increase proportion of labour force transitioning into decent employment, percent                                                 ','12.05.01',34.5000       ,'Percent                         '),
(131,'Increase percentage of employers satisfied with the training provided by the TVET institutions, percent                           ','12.06.01',40.0000       ,'Percent                         '),
(132,'Increase ratio of STEI/STEM graduates to Humanities                                                                               ','12.07.01',0.2857        ,'Ratio                           '),
(133,'Reduce Maternal Mortality ratio (Per 100,000)                                                                                     ','12.08.01',336.0000      ,'Per 100,000                     '),
(134,'Reduced Under 5 Mortality Rate (Per 1,000)                                                                                        ','12.09.01',64.0000       ,'Per 100,000                     '),
(135,'Total Fertility Rate                                                                                                              ','12.10.01',5.4000        ,'Children?                       '),
(136,'Reduce mortality due to Malaria, AIDS and TB - Malaria                                                                            ','12.11.01',13.0000       ,'?                               '),
(137,'Reduce mortality due to Malaria, AIDS and TB - AIDS related                                                                       ','12.11.02',5.0000        ,'?                               '),
(138,'Reduce mortality due to Malaria, AIDS and TB - TB                                                                                 ','12.11.03',4.0000        ,'?                               '),
(139,'Reduce NCD rates - Hypertension                                                                                                   ','12.12.01',3.2000        ,'?                               '),
(140,'Reduce NCD rates - Diabetic rate                                                                                                  ','12.12.02',2.5000        ,'?                               '),
(141,'Reduce NCD rates - Cancer                                                                                                         ','12.12.03',1.8000        ,'?                               '),
(142,'Reduce NCD rates - Alcohol abuse                                                                                                  ','12.12.04',5.8000        ,'?                               '),
(143,'Reduce teenage Pregnancy                                                                                                          ','12.13.01',25.0000       ,'?                               '),
(144,'Increase access to safe water supply - Rural                                                                                      ','12.14.01',73.0000       ,'?                               '),
(145,'Increase access to safe water supply - Urban                                                                                      ','12.14.02',74.0000       ,'?                               '),
(146,'Increase access to basic sanitation - Improved toilet coverage                                                                    ','12.15.01',19.0000       ,'?                               '),
(147,'Increase access to basic sanitation - Improved handwashing facility                                                               ','12.15.02',34.0000       ,'?                               '),
(148,'Reduce prevalence of child disability                                                                                             ','12.16.01',13.0000       ,'?                               '),
(149,'Reduce unmet need for Family Planning                                                                                             ','12.17.01',28.0000       ,'?                               '),
(150,'Increase proportion of workplaces with occupational health services                                                               ','12.18.01',20.0000       ,'?                               '),
(151,'Increase Gender gap index                                                                                                         ','12.19.01',0.5230        ,'?                               '),
(152,'Reduce GBV prevalence                                                                                                             ','12.20.01',56.0000       ,'?                               '),
(153,'Improve compliance to the gender & equity certificate                                                                             ','12.21.01',95.0000       ,'?                               '),
(154,'Increase proportion of population with access to Universal health care, percent                                                   ','12.22.01',44.0000       ,'Percent                         '),
(155,'Proportion of population with access to social insurance, percent                                                                 ','12.23.01',5.0000        ,'Percent                         '),
(156,'Improve Uganda’s ranking in niche sports - Football                                                                               ','12.24.01',77.0000       ,'Ranking                         '),
(157,'Improve Uganda’s ranking in niche sports - Netball                                                                                ','12.24.02',6.0000        ,'Ranking                         '),
(158,'Improve Uganda’s ranking in niche sports - Athletics                                                                              ','12.24.03',9.0000        ,'Ranking                         '),
(159,'Improve Uganda’s ranking in niche sports - Rugby                                                                                  ','12.24.04',18.0000       ,'Ranking                         '),
(160,'Increase proportion of workplaces with health wellness programme, percent                                                         ','12.25.01',53.0000       ,'Percent                         '),
(161,'Percentage share of national labour force engaged in subsistence                                                                  ','12.26.01',39.5000       ,'?                               '),
(162,'Global Innovation Index (percent)                                                                                                 ','13.01.01',25.3200       ,'Percent                         '),
(163,'Gross Expenditure on R&D (GERD) as a percent of GDP                                                                               ','13.02.01',0.4000        ,'Percent of GDP                  '),
(164,'Business enterprise sector spending on R&D (percent of GDP)                                                                       ','13.03.01',0.0100        ,'Percent of GDP                  '),
(165,'Increase percentage of Households participating in public development initiatives                                                 ','14.01.01',60.0000       ,'Percent                         '),
(166,'Increase proportion of the population informed about national programmes                                                          ','14.02.01',30.0000       ,'Percent                         '),
(167,'Improve percentage of vulnerable and marginalized persons empowered                                                               ','14.03.01',1.5000        ,'Percent                         '),
(168,'Increase participation in government programmes - Level of participation in electoral processes (voter turnout)                   ','14.04.01',69.0000       ,'Percent                         '),
(169,'Increase participation in government programmes - Households’ participation in saving schemes (percent)                           ','14.04.02',10.0000       ,'Percent                         '),
(170,'Improve staffing levels for national guidance and community mobilization functions at all levels - Central Level                  ','14.05.01',84.0000       ,'?                               '),
(171,'Improve staffing levels for national guidance and community mobilization functions at all levels - LG Level                       ','14.05.02',86.0000       ,'?                               '),
(172,'Reduce incidence of unethical behavior (corruption, crime rate, theft, immorality) - Corruption perception index                  ','14.06.01',26.0000       ,'?                               '),
(173,'Reduce incidence of unethical behavior (corruption, crime rate, theft, immorality) - Crime rate per 100,000 persons               ','14.06.02',612.0000      ,'Crimes per 100,000 Persons      '),
(174,'Level of satisfaction with public service delivery                                                                                ','14.07.01',50.0000       ,'?                               '),
(175,'Government effectiveness index (1)																								','14.08.01',-0.5000       ,'?                               '),
(176,'Reduce percentage of backlog cases in the system                                                                                  ','15.01.01',18.0000       ,'Percent                         '),
(177,'Increase disposal rate of cases                                                                                                   ','15.02.01',60.0000       ,'?                               '),
(178,'Increase percentage of districts with one stop frontline JLOS service points                                                      ','15.03.01',67.5000       ,'Percent                         '),
(179,'Improve Corruption Perception Index                                                                                               ','15.04.01',26.0000       ,'?                               '),
(180,'Increase percentage expenditure on R&D                                                                                            ','15.05.01',0.0100        ,'?                               '),
(181,'Increase expenditure on R&D by Security Sector (UGX Billion)                                                                      ','15.06.01',7.0000        ,'UGX Billion                     '),
(182,'Increase Democratic index                                                                                                         ','15.07.01',6.5000        ,'?                               '),
(183,'Attain a 25 percent enrolment in the National service                                                                             ','15.08.01',0.0000        ,'Enrolment (Percent)             '),
(184,'Proportion of eligible voters registered                                                                                          ','15.09.01',80.0000       ,'Percent                         '),
(185,'Increase percentage of citizens engaged in electoral process                                                                      ','15.10.01',80.0000       ,'Percent                         '),
(186,'Improve Peace Index                                                                                                               ','15.11.01',2.1960        ,'?                               '),
(187,'Improve level of implementation of the Settlement Transformative Agenda, percent                                                  ','15.12.01',40.0000       ,'Percent                         '),
(188,'Increase Government effectiveness index (2)																				        ','16.01.01',-0.5800       ,'?                               '),
(189,'Improve Global competitiveness index                                                                                              ','16.02.01',48.9000       ,'?                               '),
(190,'Reduce corruption perception index                                                                                                ','16.03.01',26.0000       ,'?                               '),
(191,'Reduce poverty in the lagging regions of Uganda - Bukedi                                                                          ','17.01.01',43.7000       ,'?                               '),
(192,'Reduce poverty in the lagging regions of Uganda - Busoga                                                                          ','17.01.02',37.5000       ,'?                               '),
(193,'Reduce poverty in the lagging regions of Uganda - Elgon                                                                           ','17.01.03',34.5000       ,'?                               '),
(194,'Reduce poverty in the lagging regions of Uganda - West Nile                                                                       ','17.01.04',34.9000       ,'?                               '),
(195,'Reduce poverty in the lagging regions of Uganda - Karamoja                                                                        ','17.01.05',60.2000       ,'?                               '),
(196,'Reduce poverty in the lagging regions of Uganda - Acholi                                                                          ','17.01.06',33.4000       ,'?                               '),
(197,'Reduce poverty in the lagging regions of Uganda - Teso                                                                            ','17.01.07',25.1000       ,'?                               '),
(198,'Reduce poverty in the lagging regions of Uganda - Bunyoro                                                                         ','17.01.08',17.3000       ,'?                               '),
(199,'Increase average monthly household income (UGX)                                                                                   ','17.02.01',416000.0000   ,'UGX                             '),
(200,'Improve proportion of households reporting better living conditions, percent                                                      ','17.03.01',45.0000       ,'Percent                         '),
(201,'Attain maximum alignment between the Annual Budgets and the NDPIII at national and programme level                                ','18.01.01',60.0000       ,'?                               '),
(202,'Improve achievement of NDPIII targets, percent                                                                                    ','18.02.01',0.0000        ,'Percent                         '),
(203,'Maintain single digit Inflation rate                                                                                              ','18.03.01',3.4000        ,'Percent                         '),
(204,'Improve Private sector credit (percent GDP)                                                                                       ','18.04.01',11.2000       ,'Percent GDP                     '),
(205,'Increase GDP growth rate                                                                                                          ','18.05.01',6.2000        ,'Percent                         '),
(206,'Increase Revenue to GDP ratio                                                                                                     ','18.06.01',12.9500       ,'?                               '),
(207,'Increase Proportion of direct budget transfers to local government                                                                ','18.07.01',12.0000       ,'Percent                         '),
(208,'Improve on World Bank Statistical Capacity Indicator (WBSCI) score                                                                ','18.08.01',74.4000       ,'?                               '),
(209,'Government Effectiveness index (3)                                                                                                ','18.09.01',-0.5000       ,'?                               '),
(210,'Proportion of NDPIII baseline indicators up-to-date & updated                                                                     ','18.10.01',60.0000       ,'Percent                         ');

--select * from I;

select '1.5'
go

--use Uganda;
--go
--select
--	'('													+
--	convert(nchar(3),ProgrammeKeyResultID)				+','+
--	char(39)+convert(nchar(130),Name)+char(39)			+','+
--	char(39)+convert(nchar(8),NDP3Reference)+char(39)	+','+
--			+convert(nchar(14),Baseline)				+','+
--	char(39)+convert(nchar(32),Units)+char(39) +
--	'),'
--from 
--	ndp3.ProgrammeKeyResults;